### ISSUE TITLE
Replace lightdm-webkit2-greeter with lightdm-gtk-greeter to avoid rotation issues

### ISSUE THREAD

**Issue by atom-p** [cawilliamson/ansible-gpdpocket#1]
Having installed Antergos with the latest iso (17.8) and then running the bootstrap script as the instructions state I'm finding an interesting minor issue with the login screen rotation.

On boot the login screen (lightdm) rotates to the correct orientation, but retains the prior resolution of 1200x1920, cutting off the bottom of the login screen.

![img_20170804_163749](https://user-images.githubusercontent.com/30729068/28976177-ca8e7ad6-7934-11e7-8d6e-0ed267b22f29.jpg)

Having logged in and then out again, or alternatively restarting lightdm, the login screen has no corrective rotation.

![img_20170804_163931](https://user-images.githubusercontent.com/30729068/28976215-f6dbbb9e-7934-11e7-924b-8055df778a69.jpg)

All other screen and touch rotation (besides grub) appears to be functioning as intended.

**Comment by cawilliamson** [comment]
This is very odd - could you try manually running the following over SSH while the display is in that state?

`/usr/local/sbin/gpd-rotate --screen=1 --touchscreen=1`

Could you also run the following and provide the output while the display is in that state?

`ps aux |grep -i xorg`

It's very strange that your display rotates incorrectly after logout too - there's no reason your DM should be resetting the orientation at all after logout but I will investigate this.

Apologies for the delay - I've been heavily focused on the bootstrap-iso work.

**Comment by atom-p** [comment]
Over SSH the gpd-rotate command had no noticeable effect on the screen in its incorrectly rotated state.

I logged out/restarted lightdm, offering the display as seen in my second image above, ran the gpd-rotate command over SSH and it rotated the display, but as seen in the incorrectly rotated state in the first picture.

The output of the second command is:

```
root       692  6.1  0.6 427404 49124 tty7     Ssl+ 12:46   0:48 /usr/lib/xorg-server/Xorg :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
tom       1161  0.0  0.0  10796  2136 pts/0    S+   13:00   0:00 grep -i xorg
```

A couple of additional points that I've just noticed while trying these out:
 - The touchscreen on the login screen in the above state works fine - it is rotated.
 - The cursor will actually move into that black space. Whereas before I thought it would be 'off the display' as it were, it's actually possible to both touch and move the cursor into that black space. I think this might indicate that it's more an issue of lightdm not recognising the changes to the display properly, rather than the command not working?

**Comment by cawilliamson** [comment]
This does sound like an issue with lightdm but I did use lightdm on Mint and didn't have this issue.

I don't suppose there's a newer version of lightdm available is there?

**Comment by atom-p** [comment]
Both the Arch and Ubuntu Zesty repos are using lightdm 1.22 which is the latest release.

I've made some progress. I switched from Antergos' lightdm-webkit2-greeter to the lightdm-gtk-greeter in the lightdm.conf file. This rotates properly when gpd-rotate tells it to! This could be why Mint behaved differently to Antergos, it may have been using something other than the webkit2 greeter.

It would appear that this problem is related to the lightdm-webkit2-greeter.

**Comment by cawilliamson** [comment]
Ah, that explains a lot!

Hmm, webkit2-greeter - so it's basically a webpage (for want of a better term!)

Yeah I can imagine that may be trouble rotating - probably worth filing a bug with them since ultimately all we're doing here is:

xrandr --display DSI1 --rotate left

The only "solution" I can think of adding from the ansible side of things is to enforce lightdm-gtk-greeter where the lightdm.conf file exists. What are your views on that?

**Comment by atom-p** [comment]
It's the solution that I went with ultimately. The ansible script will also need to pull and install the lightdm-gtk-greeter package from the Arch repos in addition to the config change, but that's no great hurdle, it's just another package to download during the "Installing necessary packages" stage.

**Comment by cawilliamson** [comment]
I'm re-opening this one as an enhancement ticket - I would still like to add this - just been distracted with the ansible-iso re-write, fedora and manjaro.

**Comment by cawilliamson** [comment]
I have just added a fix for this - webkit2-greeter should be replaced with gtk-greeter (but only if webkit2-greeter was already installed.)

This only applies to Arch-based distros because they're the only ones with the package even available!
