### ISSUE TITLE
bootstrap-iso fails if the removable volume has a space in its name

### ISSUE THREAD

**Issue by antichamber** [cawilliamson/ansible-gpdpocket#10]
After attempting to bootstrap my Kali iso again, it ran into an error saying a directory didn't exist. My usb drive's main volume was called "New Volume" and the directory that it couldn't reach was /media/root/New

**Comment by cawilliamson** [comment]
Why would you use your volume name anyway?

You're just supposed to run:

bootstrap-iso.sh <iso-filename>

Am I missing something?
