### ISSUE TITLE
Trusty is 14.04 LTS. Xenial is 16.04 LTS.

### ISSUE THREAD

**Issue by Redsandro** [cawilliamson/ansible-gpdpocket#100]
Perhaps change `trusty` into `xenial` in [bootstrap-system.sh:27](https://github.com/cawilliamson/ansible-gpdpocket/blob/master/bootstrap-system.sh#L27):

```
echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' > /etc/apt/sources.list.d/ansible.list
```

**Comment by cawilliamson** [comment]
I'm using `trusty` because it needs to work on Debian also and ultimately makes very little difference since trusty branch of the ansible repo uses the same version as xenial anyway. :)

**Comment by Redsandro** [comment]
Ok. Thanks for the quick reply! :smiley:
