### ISSUE TITLE
initramfs-tools errors

### ISSUE THREAD

**Issue by greg-the-maker** [cawilliamson/ansible-gpdpocket#102]
I keep seeing errors referencing initrmfs-tools, the latest is pasted below....

> 
> viciouspenguin@Pocket:~/Downloads$ sudo apt install boinc
> [sudo] password for viciouspenguin: 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following additional packages will be installed:
>   boinc-client boinc-manager libboinc7 libjavascriptcoregtk-1.0-0
>   libwebkitgtk-1.0-0 libwxbase3.0-0v5 libwxgtk-webview3.0-0v5 libwxgtk3.0-0v5
> Suggested packages:
>   boinc-client-opencl boinc-client-fglrx boinc-client-nvidia-cuda
> The following NEW packages will be installed
>   boinc boinc-client boinc-manager libboinc7 libjavascriptcoregtk-1.0-0
>   libwebkitgtk-1.0-0 libwxbase3.0-0v5 libwxgtk-webview3.0-0v5 libwxgtk3.0-0v5
> 0 to upgrade, 9 to newly install, 0 to remove and 0 not to upgrade.
> 1 not fully installed or removed.
> Need to get 17.4 MB of archives.
> After this operation, 72.9 MB of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Get:1 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 libboinc7 amd64 7.6.33+dfsg-11 [363 kB]
> Get:2 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 boinc-client amd64 7.6.33+dfsg-11 [439 kB]
> Get:3 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 libwxbase3.0-0v5 amd64 3.0.2+dfsg-4 [968 kB]
> Get:4 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 libjavascriptcoregtk-1.0-0 amd64 2.4.11-3 [1,831 kB]
> Get:5 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 libwebkitgtk-1.0-0 amd64 2.4.11-3 [7,934 kB]
> Get:6 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 libwxgtk3.0-0v5 amd64 3.0.2+dfsg-4 [4,347 kB]
> Get:7 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 libwxgtk-webview3.0-0v5 amd64 3.0.2+dfsg-4 [49.5 kB]
> Get:8 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 boinc-manager amd64 7.6.33+dfsg-11 [1,423 kB]
> Get:9 http://gb.archive.ubuntu.com/ubuntu zesty/universe amd64 boinc all 7.6.33+dfsg-11 [14.7 kB]
> Fetched 17.4 MB in 7s (2,261 kB/s)                                             
> Preconfiguring packages ...
> Selecting previously unselected package libboinc7:amd64.
> (Reading database ... 209137 files and directories currently installed.)
> Preparing to unpack .../0-libboinc7_7.6.33+dfsg-11_amd64.deb ...
> Unpacking libboinc7:amd64 (7.6.33+dfsg-11) ...
> Selecting previously unselected package boinc-client.
> Preparing to unpack .../1-boinc-client_7.6.33+dfsg-11_amd64.deb ...
> Unpacking boinc-client (7.6.33+dfsg-11) ...
> Selecting previously unselected package libwxbase3.0-0v5:amd64.
> Preparing to unpack .../2-libwxbase3.0-0v5_3.0.2+dfsg-4_amd64.deb ...
> Unpacking libwxbase3.0-0v5:amd64 (3.0.2+dfsg-4) ...
> Selecting previously unselected package libjavascriptcoregtk-1.0-0:amd64.
> Preparing to unpack .../3-libjavascriptcoregtk-1.0-0_2.4.11-3_amd64.deb ...
> Unpacking libjavascriptcoregtk-1.0-0:amd64 (2.4.11-3) ...
> Selecting previously unselected package libwebkitgtk-1.0-0:amd64.
> Preparing to unpack .../4-libwebkitgtk-1.0-0_2.4.11-3_amd64.deb ...
> Unpacking libwebkitgtk-1.0-0:amd64 (2.4.11-3) ...
> Selecting previously unselected package libwxgtk3.0-0v5:amd64.
> Preparing to unpack .../5-libwxgtk3.0-0v5_3.0.2+dfsg-4_amd64.deb ...
> Unpacking libwxgtk3.0-0v5:amd64 (3.0.2+dfsg-4) ...
> Selecting previously unselected package libwxgtk-webview3.0-0v5:amd64.
> Preparing to unpack .../6-libwxgtk-webview3.0-0v5_3.0.2+dfsg-4_amd64.deb ...
> Unpacking libwxgtk-webview3.0-0v5:amd64 (3.0.2+dfsg-4) ...
> Selecting previously unselected package boinc-manager.
> Preparing to unpack .../7-boinc-manager_7.6.33+dfsg-11_amd64.deb ...
> Unpacking boinc-manager (7.6.33+dfsg-11) ...
> Selecting previously unselected package boinc.
> Preparing to unpack .../8-boinc_7.6.33+dfsg-11_all.deb ...
> Unpacking boinc (7.6.33+dfsg-11) ...
> Processing triggers for mime-support (3.60ubuntu1) ...
> Processing triggers for ureadahead (0.100.0-19) ...
> Processing triggers for desktop-file-utils (0.23-1ubuntu2) ...
> Setting up libboinc7:amd64 (7.6.33+dfsg-11) ...
> Setting up initramfs-tools (0.125ubuntu9) ...
> /var/lib/dpkg/info/initramfs-tools.postinst: 16: /var/lib/dpkg/info/initramfs-tools.postinst: update-initramfs: not found
> dpkg: error processing package initramfs-tools (--configure):
>  subprocess installed post-installation script returned error exit status 127
> Setting up libwxbase3.0-0v5:amd64 (3.0.2+dfsg-4) ...
> Processing triggers for bamfdaemon (0.5.3+17.04.20170406-0ubuntu1) ...
> Rebuilding /usr/share/applications/bamf-2.index...
> Setting up libjavascriptcoregtk-1.0-0:amd64 (2.4.11-3) ...
> Processing triggers for libc-bin (2.24-9ubuntu2.2) ...
> Processing triggers for systemd (232-21ubuntu5) ...
> Setting up libwebkitgtk-1.0-0:amd64 (2.4.11-3) ...
> Processing triggers for man-db (2.7.6.1-2) ...
> Setting up boinc-client (7.6.33+dfsg-11) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/boinc-client.service → /lib/systemd/system/boinc-client.service.
> Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
> Processing triggers for hicolor-icon-theme (0.15-1) ...
> Setting up libwxgtk3.0-0v5:amd64 (3.0.2+dfsg-4) ...
> Setting up libwxgtk-webview3.0-0v5:amd64 (3.0.2+dfsg-4) ...
> Setting up boinc-manager (7.6.33+dfsg-11) ...
> Setting up boinc (7.6.33+dfsg-11) ...
> Processing triggers for libc-bin (2.24-9ubuntu2.2) ...
> Processing triggers for systemd (232-21ubuntu5) ...
> Processing triggers for ureadahead (0.100.0-19) ...
> Errors were encountered while processing:
>  initramfs-tools
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by enthusi** [comment]
Yes, I have the same error here (built the ubuntu 17.04 image yesterday, based on "72f4249 removed all base-devel steps...") though it does not seem to affect anything.

**Comment by greg-the-maker** [comment]
I get this error during install on Ubunut 17.04 too. This was the original instance of the error.

![2017-08-21 14 42 04](https://user-images.githubusercontent.com/31005232/29613945-15912af4-8800-11e7-89be-e80e4d4ff4d4.jpg)
![2017-08-21 14 41 32](https://user-images.githubusercontent.com/31005232/29613947-170be2ca-8800-11e7-8df9-b1c210340da1.jpg)
![2017-08-21 14 06 20](https://user-images.githubusercontent.com/31005232/29613949-18a90252-8800-11e7-865a-6cc6cd333392.jpg)

**Comment by psrb191921** [comment]
Same here, tried:
sudo dpkg --configure -a
With error:
/var/lib/dpkg/info/initramfs-tools.postinst: 16: update-initramfs: not found

**Comment by psrb191921** [comment]
sudo cp /usr/sbin/update-initramfs.orig.initrfs-tools /usr/sbin/update-initramfs
Fixed the problem

**Comment by cawilliamson** [comment]
I've just added an experimental fix for this based on your work psrb191921 - that's awesome!

Let me know how it goes if you could folks - obviously I don't want people to have to copy files around manually. 👍 

Thanks!

**Comment by geoff-github** [comment]
Having the same issues as greg-the-maker on install, when I reboot I get a terminal window with the tag initramfs.  the cp command gives me an error as well.  I just did a fresh clone after the fix was posted.
![screenshot from 2017-08-23 21-42-16](https://user-images.githubusercontent.com/9980311/29645595-95aa8b76-884c-11e7-83fd-7ba86f113ba9.png)

**Comment by cawilliamson** [comment]
@geoff-github That's a different issue - you can't run those commands listed above while within a busybox recovery shell.

Could you try a clean install, then if that doesn't work - provide any information you can on a new ticket?
