### ISSUE TITLE
kali installer initrd replaced instead of patched

### ISSUE THREAD

**Issue by ITSGonzo** [cawilliamson/ansible-gpdpocket#104]
Playbook fails at this task and terminates:

**TASK [ iso : bootstrap guest ( this may talk a while )]**

I tried building the ISO (kali 2017.1 rolling 64 gnome )on Ubuntu 16.10 and kali 2017.1 rolling. both fail at this step.

**Comment by ITSGonzo** [comment]
Here is a pastbin dump of one of the build attempts, note got the same error when building kail iso on ubuntu and kali host os. 
https://pastebin.com/KMiTt5ZT

**Comment by RevoltsRevolution** [comment]
Oh that sounds exciting! Please update the thread about your Kali progress - I'm trying to get Kali on the GPD for weeks now without any success.

**Comment by whoismike** [comment]
Same issue, similar logs.  I just started trying to build this, and haven't spent alot of time troubleshooting yet.  (I'm green with Ansible.)

Tried building on kali 2017.1 rolling and ubuntu-16.04.3-desktop.  Attached the logs of the 16.04.3 at: https://pastebin.com/QYEjVCEn

root@ubuntu:~# uname -a
Linux ubuntu 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Happy to help test if someone is further along troubleshooting than me.  16.0.4 desktop iso builds fine...

**Comment by cawilliamson** [comment]
I've just added a fix for this one - it looks like the Kali ISO doesn't have grub2 present by default *but* it shouldn't need to since it wont be used anyway! So - what I've done is disabled the step for updating grub config whilst bootstrapping from an ISO.

In short:

- ISOs don't update grub config.
- System bootstrap / update DOES update grub config.

From my side this looks to resolve the ISO build problem and creates a final ISO image.

I'm closing this ticket off for now since this issue is resolved. If there are other issues please feel free to raise another ticket though and thanks for the info!

**Comment by whoismike** [comment]
Playbook finishes and builds an iso. (yay!)  ISO will boot on gpd, but kali boot menus/options don't work as they're supposed to... The boot "live" option fails to boot at all, The install options all boot into a live mode (including text install.)  Progress, but not quite working yet.  Giving up for now, but may open another ticket if I can figure out something more specific to report.  For now, this is just a "it doesn't work yet" follow-up report...

**Comment by cawilliamson** [comment]
@whoismike I think I know how to fix this - leave it with me.

**Comment by Herst** [comment]
@cawilliamson I wonder the the same, http://unix.stackexchange.com/ is also full of questions about it.

**Comment by ITSGonzo** [comment]
Highly mobile, discrete, self contained and easily concealable + screen / battery  = pentester's dream.  =)

**Comment by whoismike** [comment]
Ah, cool if you know how to fix it...  I was just checking here to see if anyone had an update to start poking at the issue again.  For pentesters, the GPD pocket is a nice platform for being discreet and easy to have with you when you need it.  ITSGonzo has it right..  I suspect that many of us saw the potential and ordered one to get another tool in the tool chest without doing alot of checking on hardware compatibility. It isn't sudden interest, but a community of people who saw this gadget as fitting a particular set of needs we have. I figured that if an official Ubuntu release would be supported, that we'd eventually be able to get Kali working on the gpd pocket too.  Thanks for reopening this issue and working it.
