### ISSUE TITLE
Extract squashfs fails on Debian 9 DVD ISO

### ISSUE THREAD

**Issue by DavidCWGA** [cawilliamson/ansible-gpdpocket#105]
```
TASK [iso : extract squashfs image] ******************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: list object has no element 0\n\nThe error appears to have been in '/root/ansible-gpdpocket/roles/iso/tasks/main.yml': line 117, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: extract squashfs image\n  ^ here\n"}

msg: the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: list object has no element 0

The error appears to have been in '/root/ansible-gpdpocket/roles/iso/tasks/main.yml': line 117, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: extract squashfs image
  ^ here
```

**Comment by DavidCWGA** [comment]
Fails in an identical way on the regular non firmware iso: "debian-9.1.0-amd64-DVD-1.iso"

**Comment by DavidCWGA** [comment]
I guess the previous section in the log may also be relevant:

````
TASK [iso : find squashfs image] *********************************************************************************************************
ok: [localhost] => {"changed": false, "examined": 9482, "files": [], "matched": 0, "msg": ""}
````

"Files" has no content and matched is 0.

**Comment by reldred** [comment]
I ran into this myself; it only works on Live cd/dvd images not the graphical installers and not the netinstall images.

**Comment by cawilliamson** [comment]
Strangely the LiveDVD image from debian doesn't contain a squashfs image which I could find - happy to be proven wrong!

Ultimately these images are only being patched enough to get them to install on a GPD Pocket without issues so I'm afraid this isn't something I'm going to invest much time in to beyond updating the readme (which I have done) to reflect this.

More than happy to accept pull requests to support additional CD/DVD configurations but for now - I suggest just using a standard debian install image to bootstrap-iso against. :)

**Comment by DavidCWGA** [comment]
Just for reference, the ISOs I was using *are* the "standard debian install images". Debian do provide live images, but you have to dig around for them. (They're here: https://www.debian.org/CD/live/ )

I'll continue further testing with these live images.
