### ISSUE TITLE
No ethernet after setup on Debian 9

### ISSUE THREAD

**Issue by DavidCWGA** [cawilliamson/ansible-gpdpocket#106]
Because of #105, I installed plain Debian 9, and then ran bootstrap after.

I'm using a USB-C ethernet adapter, and it was working fine until bootstrap completed and I rebooted. Now the USB ethernet interface is gone, and I can only see loopback and wifi.

**Comment by DavidCWGA** [comment]
A different USB-A ethernet adapter still works fine.

**Comment by cawilliamson** [comment]
@DavidCWGA This is really one to report to @jwrdegoede - kernel is his domain, I'm just providing a build script for it. 👍
