### ISSUE TITLE
rsync isn't installed as a dependency.

### ISSUE THREAD

**Issue by Awwkaw** [cawilliamson/ansible-gpdpocket#110]
I tried bootstraping some iso's from an antergos install and got a bug with rsync missing.
Installing rsync fixed it.

I would just add rsync to the install and make a pull request but i'm not really good at git (I get an error when i try `git -p request-pull master https://www.github.com/cawilliamson/ansible-gpdpocket`). 

the fix however was just changing line 15 from:
```sh
pacman -Sy --needed --noconfirm ansible git
```
to
```sh
pacman -Sy --needed --noconfirm ansible git rsync
```

after this change my antergos install created an iso that i'm currently writing to a usb stick

**Comment by cawilliamson** [comment]
Fix added - thanks! 👍

**Comment by Awwkaw** [comment]
no problem, sorry i have to make you do this instead of just making a pull request though XD
