### ISSUE TITLE
No initial wifi on antergos bootstrapped iso

### ISSUE THREAD

**Issue by Awwkaw** [cawilliamson/ansible-gpdpocket#111]
I didn't have wifi on the bootstrapped iso.
This wouldn't be a problem if i could install the os and then get the fix from the arch wiki later, but since antergos needs internet for installation it would be really nice if the wifi worked on the bootsrapped iso.

Edit:
I could see the device with `lspci -k` but not with `iw list` or `netctl list`

**Comment by icebal** [comment]
were there any errors during the bootstrap-iso script?
try running 'sudo modprobe brcmfmac" when booted tothe bootstrap ISO.
if your able see your device when running ip link or not, please update your issue.

**Comment by Awwkaw** [comment]
That tip worked wonderfullly XD, changed topic to adding this to the readme XD

**Comment by nexus511** [comment]
What distribution do you use?

It should normally not be necessary to manually load the brcmfmac driver as this should be done automatically after bootstrapping. Thus that might be an issue. Not on the documentation but rather on the build-scripts.

**Comment by Awwkaw** [comment]
Sorry for changing it, i thought it was intentional

**Comment by Awwkaw** [comment]
I might have bootstrapped it wrong the first time, the second time i tried it gave me lots of wifi
