### ISSUE TITLE
Gnome3 slow as hell

### ISSUE THREAD

**Issue by psrb191921** [cawilliamson/ansible-gpdpocket#112]
Ubuntu 17.10 with gnome3
Gnome-shell eats all cpu when I e.g. use touch display to move window around or click to start any app. When I click with mouse it goes ok. Is it normal behaviour? I've used ubuntu budgie with respin scripts before, the speeds was ok

**Comment by DavidCWGA** [comment]
Same experiences here. If you avoid the touch screen everything is fine. Don't know why.

**Comment by DavidCWGA** [comment]
Try "sudo gpd-rotate" and try the touchscreen again.
