### ISSUE TITLE
No battery indicator after building Ubuntu 16.04.3 LTS ISO

### ISSUE THREAD

**Issue by marcusteaton** [cawilliamson/ansible-gpdpocket#116]
Hello,

Not sure if this is on the ISO building portion or the OS itself, but after building a 16.04.3 LTS ISO I have no battery indicator and Ubuntu is acting like I don't have a battery. I'm not sure what info you need but I'll be happy to get it for you. Apologies as I'm not super used to filing bugs.

Thank you!

**Comment by icebal** [comment]
can you provide the following information?

1. run sudo gpd-update and post any errors
2. reboot after gpd-update
3. output of uname -r

**Comment by marcusteaton** [comment]
No errors during gpd-update. Rebooted and the battery indicator was there!

You can file this one under PEBCAK/Layer 8 issue. ;)

For the record, I'm on 4.13.0-rc5-jwrdegoede after the upgrade.

Thank you for the help!

**Comment by lucasdurand** [comment]
Hey, so I'm trying to deal with a battery indicator issue but can't seem to get past 4.13.0-rc0-bootstrap. I'm running gpd-update and rebooting, but no luck. Any ideas?
