### ISSUE TITLE
Devuan-Support, planned?

### ISSUE THREAD

**Issue by zedr0k** [cawilliamson/ansible-gpdpocket#120]
when all the major-issues are fixed, have you planned to implement support for other distros like devuan (or maybe void)?
thanks for your work!

**Comment by Awwkaw** [comment]
Devuan might actually be supported, since it's debian based (i'm don't think the bootstrap requires systemd, but i'm not sure)
Rememver to rename the iso to something like 'devuandebainbased.iso', since the bootstrap-iso.sh files checks the name of the iso

**Comment by Herst** [comment]
Might mean quite some work, e.g. <https://github.com/cawilliamson/ansible-gpdpocket/blob/master/roles/power/files/gpd-fan.service> is a systemd servicefile which would have to converted for Sys V init. Therefore, I am guessing that support for it is unlikely to be going to be implemented without some work from motivated contributors (which preferably are using the distro themselves, dogfooding is important).

**Comment by cawilliamson** [comment]
Ultimately I don't intend to add any new major distros to the list but I am completely open to pull requests so if anyone wants to put in the effort to get this working - that's cool but I personally don't intend to do this - sorry!

I've got enough work just keeping the current list of distros working. :)
