### ISSUE TITLE
bootstraped antergos.iso installs NON bootstrapped os

### ISSUE THREAD

**Issue by Awwkaw** [cawilliamson/ansible-gpdpocket#122]
I've been trying to install antergos, and after succeding in installing the os is not bootstrapped, this might be intented, but i'm not sure.

I cannot get wifi to work, so i cannot bootstrap the system ;-( 

Important note: i installed the kde version (it's so smooth, but no wifi ;-( ) if that's of any importance

**Comment by cawilliamson** [comment]
Ok so I don't really know how Antergos does things *but* on ArchLinux you install entirely from command line. If that's the same with Antergos

**Comment by Awwkaw** [comment]
I think you can reclose it.
I'm pretty sure Antergos is installed via a net installer, meaning that iit's unsupported (I managed to rebootstrap using usb ether to an android device, and then it hit me that it might be a net installer).

**Comment by snazzybunny** [comment]
Antergos is a live cd with the option to install to disk. It works fine for me.

**Comment by Awwkaw** [comment]
I don't know why it didn't work then, i could however, not install without internet, which is why i thought it was a net installer.
