### ISSUE TITLE
Desktop is badly scaled (Ubuntu 17.04).

### ISSUE THREAD

**Issue by greg-the-maker** [cawilliamson/ansible-gpdpocket#123]
xrandr reports correct resolution 1200x1920. I don't know how to fix it and I can't see any of the settings windows as they are off screen......

![2017-08-25 13 45 13](https://user-images.githubusercontent.com/31005232/29714573-bdcf85de-899b-11e7-9fdd-bc259680f015.jpg)

**Comment by Herst** [comment]
I had a similar issue and as a workaround I fixed it by using the Tweak Tool to set the Window scaling (under "Windows") to 1 and instead setting the font scaling factor (under "Fonts") to "1,34".

**Comment by seaplusplus** [comment]
I had the same issue.  If you go to display setting you can hold alt and left mouse click the window and drag it up so you can adjust the scale factor.

**Comment by icebal** [comment]
can one of you guys run 'xrandr --output eDP1 --scale 1.20x1.20" and see if that helps? without the tweak tool of course. this should be a sane default for all DE/WMs.

**Comment by greg-the-maker** [comment]
Yup, that worked!

**Comment by maxengel** [comment]
I'm experiencing this as well.

**Comment by icebal** [comment]
it looks like this is going to be an issue with gnome, as well as unity. looks like the following 2 things will fix it:
gsettings set org.gnome.desktop.interface scaling-factor 2 #only whole numbers, scales only ui
xrandr --output eDP1 --scale --panning  1.25x1.25 #zooms out the scaling of the display itself, to better fine tune scaling. --panning allows the use of the whole screen
