### ISSUE TITLE
4.13 release to include Hans's work?

### ISSUE THREAD

**Issue by voobscout** [cawilliamson/ansible-gpdpocket#127]
It's more of a question, not an issue, but here seems to be the appropriate place to ask, since Hans's repo has no issues flag.

Will Hans's patches be mainlined into upcoming 4.13 or is it unclear atm and we should just fend for ourselves until later? 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Herst** [comment]
See <https://www.reddit.com/r/GPDPocket/comments/6uffmz/gpd_releases_link_to_pockets_ubuntu_kernel/dlsh3vh/>.
