### ISSUE TITLE
elementary OS support

### ISSUE THREAD

**Issue by maxengel** [cawilliamson/ansible-gpdpocket#130]
It would be nice if the Ubuntu-based elementary OS (https://elementary.io/) was supported when creating the image from the ISO.

**Comment by Awwkaw** [comment]
It should be, as Ubuntu is debian based and elementary os is thus debian based.

**Comment by maxengel** [comment]
how should I name the ISO? the current name isn't recognized when running bootstrap.sh.

**Comment by Awwkaw** [comment]
anything that includes: debian ubuntu or kali. Only the bigger debian names are defined in the list.

**Comment by maxengel** [comment]
I changed the name to Ubuntu, but it didn't build correctly...

On Aug 28, 2017, at 07:27 PM, Awwkaw <notifications@github.com> wrote:

anything that includes: debian ubuntu or kali. Only the bigger debian names are defined in the list.

**Comment by cawilliamson** [comment]
I'm not looking to add additional distros at the moment - if you wish to submit a pull request that would be great. 👍
