### ISSUE TITLE
change standard output iso directory from root

### ISSUE THREAD

**Issue by maxengel** [cawilliamson/ansible-gpdpocket#131]
Right now the bootstrap.iso is being created with ownership by the root user and lives in /root. It would be better if it was instead in the directory that the project was pulled into and set to -777 and owned by the user who created it. This would make the image easier to burn with Etcher.

**Comment by cawilliamson** [comment]
I don't see this as an issue and I'm not sure what this obsession with etcher is - just `sudo dd` it to a USB drive.

If you want this feature - I'd welcome a pull request adding it but it's not one I plan to spend time on - sorry!
