### ISSUE TITLE
Fix for rotation issues

### ISSUE THREAD

**Issue by nexus511** [cawilliamson/ansible-gpdpocket#134]
Hi,

I have currently not the time to create a pull request. I might do this later.

After looking at the rotation script, I don't think that this is basically the right approach for the "issue". A better and really stable solution is just configure X11 to properly rotate.

You can find the necessary configurations here:

- https://github.com/nexus511/gpd-ubuntu-packages/blob/feature/switch_to_X11_config/packages/gpdpocket-xorg/files/config/40-monitor.conf
- https://github.com/nexus511/gpd-ubuntu-packages/blob/feature/switch_to_X11_config/packages/gpdpocket-xorg/files/config/99-touchscreen.conf

On my image building tree, I just removed your script and placed those configurations in the place instead. Rotation will then be set on touch and display even before that X-server starts.

**Comment by enthusi** [comment]
Would this also solve SDL-fullscreen issues?

**Comment by nexus511** [comment]
Dunno. Not using any SDL applications in fullscreen on the pocket though.

Maybe you could test that or tell me what SDL application you are using?

**Comment by enthusi** [comment]
I realized when using this here with -fullscreen option:
https://github.com/bspruck/handy-fork
If you want I can dig up a more straight forward example.

**Comment by nexus511** [comment]
Well, let me say it like this: The X server is rotated using the xrandr extensions. When SDL is ignoring this fact, someone might first question, if this is really an X11/driver or rather an SDL bug.

I will (for now) not invest time to test this as there are more important things to get straight. I am pretty sure that rotating the display using the Xorg configuration is the proper way to get this done. This might fix SDL issues. So if you find time to test it, please share your experience.

**Comment by enthusi** [comment]
I have checked another SDL tool with fullscreen option.
It uses SDL 2 (might be unrelated) and has no issues. So I can confirm that SDL (at least as of 2.0) is capable of rendering proper fullscreen. I agree the issue is rather in the code than in the config/OS.

**Comment by cawilliamson** [comment]
I agree - the script sucked and was a hacky workaround.

If these config changes work that's great - previously I tried this approach but it simply did not work (like - AT ALL.)

Feel free to submit a PR and I'll merge it - this would be a positive change. 👍
