### ISSUE TITLE
Wrong kernel loaded on bootstrapped Arch ISO

### ISSUE THREAD

**Issue by Onyros** [cawilliamson/ansible-gpdpocket#14]
Successfully bootstrapped the latest Arch Linux ISO_2017.08.01, and booted the ISO with the `nomodeset fbcon=rotate:1` kernel parameters.

Wireless interface is not loaded, checked with `lsmod`, though it is present in `lspci`. Just tried a bootstrapped Ubuntu image and interface was up and running. It is also working in the original Windows installation. Cannot `modrobe brcmfmac` as there is no folder entry for the current ISO kernel modules (4.12.3-1-ARCH):

`modprobe: FATAL: module brcmfmac not found in directory /lib/modules/4.12.3-1-ARCH`

Let me know if you need any extra info that I haven't provided here, cheers!

**Comment by cawilliamson** [comment]
Nope that's all the information I needed!

It's booting the stock arch kernel and shouldn't be - I'll look in to this further but it may be later on today (due to work.)

**Comment by cawilliamson** [comment]
I believe this is now fixed - could you test and let me know the outcome? :)

**Comment by Onyros** [comment]
I'll try as soon as I get back home from work! Thanks! ;)

**Comment by cawilliamson** [comment]
Cool, no worries!

I'll await your feedback before closing this one.

**Comment by Onyros** [comment]
Hello, again! Just did a clean repo clone, rebuilt the Archiso, but it's still booting the Arch kernel (4.12.3-1-ARCH), so still no cigar... ;)

**Comment by cawilliamson** [comment]
Sorry - it's been "Debian day!"

Just building an arch ISO now and will test shortly and report back.

**Comment by cawilliamson** [comment]
I'm a bit mystified about this...

I've just built an Arch ISO, booted it (default options) and ran `uname -a` and I get:

`Linux archiso 4.13.0-rc0-bootstrap <snip>`

Also, `modprobe brcmfmac` works great for me.

Are you sure you're writing the *NEW* image to your USB drive for installation and not the old one? The new image should be at ~/bootstrap.iso

**Comment by Onyros** [comment]
I've just rebuilt the ISO, double checked, getting the same result, so this is definitely something on my side. I'm as dumbfounded as you are right now... My bootstrapped image gets written to /root as I use sudo to run the ISO bootstrapping script, but I can't see how that would be the problem. If it's building correctly on your side, just close it and I'll figure it out!

Thank you for taking the time, cheers ;)

**Comment by cawilliamson** [comment]
@Onyros my point was - are you certain you are writing the correct image to USB? The output you provided sounds like an unmodified image to me.

**Comment by Onyros** [comment]
Yes, I am quite certain. I deleted the previous ISO, went through the bootstrapping process all over again and then dd'd the new resulting ISO.

I basically started the process from scratch, cloned the repo afresh and started all over to make sure I hadn't missed anything.

**Comment by cawilliamson** [comment]
On the resulting ISO can you run the following?

`ls -l /lib/modules/`

**Comment by Onyros** [comment]
Sorry it took me this long to reply:

`total 0`
`irwxr-xr-x 3 root root 335 Aug    4 14:04 4.13.0-rc0-bootstrap`

**Comment by cawilliamson** [comment]
Tell you what would be useful actually!

Could you install the package pastebinit (using the package manager of the distro you're using to build this ISO) and then run the following:

`bash bootstrap-iso <filename here> 2>&1 | pastebinit`

Then provide me the URL or the copy/pasted content to this ticket?

**Comment by sweisman** [comment]
I am having a similar problem. Create the Arch GPD ISO (using 2017.08), write the new ISO (definitely the correct bootstrap one), boot up, there's the correct /lib/modules/4.13.0-rc0-bootstrap directory, but 4.12.3 is running (and no 4.12.3 modules). The text is oriented the wrong way. I have a USB Ethernet dongle, using a completely standard RTL device, and it is not recognized.

**Comment by sweisman** [comment]
As requested.

[root@gorilla:/site/repo/ansible-gpdpocket]$ bash bootstrap-iso.sh /site/media/archlinux-2017.08.01-x86_64.iso 2>&1 | pastebinit 

https://pastebin.com/paXLyUmW

**Comment by sweisman** [comment]
This is a bug:

**Comment by sweisman** [comment]
This looks relevant:

TASK [boot : fetch latest jwrdegoede kernel sources (this may take a while)] **************************************************************************************************************************************************************************************************************************************************
skipping: [localhost]
 
TASK [boot : build new kernel (this may take a while)] ************************************************************************************************************************************************************************************************************************************************************************
skipping: [localhost]
 
TASK [boot : install kernel modules (this may take a while)] ******************************************************************************************************************************************************************************************************************************************************************
skipping: [localhost]
 
TASK [boot : install new kernel] **********************************************************************************************************************************************************************************************************************************************************************************************
skipping: [localhost]
 
TASK [boot : clean up kernel build directory] *********************************************************************************************************************************************************************************************************************************************************************************
skipping: [localhost]

**Comment by sweisman** [comment]
I installed using the stock ISO and ran bootstrap-system.sh and it seems to work properly. Reboot brought the screen up properly once past the bootloader. I had to modify the bootloader entries because the kernel files do not use the same names.

**Comment by cawilliamson** [comment]
Ok so I'm not massively worried about it reinstalling those package - not like you're going to bootstrap an ISO every 5mins.

The skipped steps are expected - we don't build a kernel from source code when bootstrapping (would take too long) so we deploy the bootstrap kernel (pre-built.)

The strange part is:
```
+ cp /var/tmp/bootstrap-iso/squashfs/boot/initrd.img-4.13.0-rc0-bootstrap /var/tmp/bootstrap-iso/arch/boot/x86_64/archiso.img
+ cp /var/tmp/bootstrap-iso/squashfs/boot/vmlinuz-4.13.0-rc0-bootstrap /var/tmp/bootstrap-iso/arch/boot/x86_64/vmlinuz
```

This clearly states that it's overwriting the default arch kernel with the bootstrap kernel so I'm really not understanding where the arch kernel is coming from here. Can one of you fine folks boot your bootstrapped ISO and hit tab on the grub boot menu option and let me know what path is being called for the vmlinuz image?

I'm really puzzled on this one.

**Comment by sweisman** [comment]
I will get back to you on that. But I'm right in the middle of a lengthy kernel compile ATM. Speaking of which, is there a way to do an update without the kernel?

**Comment by cawilliamson** [comment]
There currently isn't but I have been thinking about two approaches for this:

1.) Offer pre-compiled up-to-date kernels (basically pull them every hour on my server, compile them and then push them to the GPD Pocket the next time `gpd-update` is run.)

2.) Simply add a `--skip-kernel` type flag to`gpd-update` but I think ultimately having the gpd-pocket compile its own kernel is kinda sucky (impressive... but sucky!) so I'm likely going to go with option #1 - perhaps with an option to compile your own kernel if you choose to (for security, etc.)

**Comment by sweisman** [comment]
Option #1 does sound good. Probably not much harder than offering the
pre-built kernel for the bootstrap. It might be four cores, but they are
obviously hobbled in some way. Kernel compiles don't take this long on a
current generation i5, do they?

**Comment by sweisman** [comment]
I still need to get back to you on the ISO.

Got X working. I use OpenBox without a display manager. I log into the the console and startx. X takes a LONG time to start, and it starts in the default tablet mode.

I believe Ubuntu booted to its GDM very fast, and logging in was also pretty fast. Is there some way to speed this up? My desktop is nearly instantaneous using the same xinitrc. I don't start that much either.

How do I change the default orientation with my own xinitrc? Putting in the needed xrandr (rotate right) in the file does not work.

**Comment by atom-p** [comment]
sweisman, out of interest what does your dmesg output during that long X start?

I've had issues with delayed Gnome starts due to intel_sst_acpi errors.

**Comment by cawilliamson** [comment]
@sweisman - you could likely just add the following:

`systemctl start gpd-rotate`

That's not a supported config though and I don't really intend to add it since it's a pretty non-standard way of doing things. In my opinion you'd be better off using something ultra lightweight like SLiM or lightdm. Up to you though!

**Comment by atom-p** [comment]
An update on where I'm at as my issue was merged into here.

I successfully created a bootstrapped Antergos ISO, it boots to the Gnome live environment, and even has the revised scaling setting. However, it does not have the screen rotated, nor does it allow for any input whatsoever. No keyboard, no trackpoint and no external keyboard. It's really weird and makes troubleshooting practically impossible.

The current permanent install is a fresh copy of the default Antergos install, bootstrapped afterwards. That continues to have my original intel_sst_acpi errors, and also a new "a start job is running for -.device" timeout on boot as well. Thanks to gpd-update that install has the option of booting from the bootstrap kernel and a fresh build of Hans' kernel, both have the same issues.

**Comment by cawilliamson** [comment]
@atom-p: It may be possible to boot with `rescue` boot option to avoid getting all the way to a desktop - at least that way you can poke around and see what's going on.

I'm most keen to know what kernel is running on the latest bootstrapped ISO you've created: `uname -a` output would be very helpful.

On a side note - which BIOS are you running? (original, ubuntu version or latest?)

**Comment by atom-p** [comment]
I've tried the "Non-graphical fallback" option that the livedisk offers, however it returns that it cannot find vmlinuz and then reports "Failure to start loader.efi: (14) Not Found".

On the latest GPD released BIOS (20170705) - Just reflashed it to be sure. (I forgot that that nukes the Antergos EFI entry too, oops).

**Comment by atom-p** [comment]
I got the boot options working, uname -a output on the bootstrapped Antergos ISO is:

`Linux ant-17.8 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux`

So it looks like the Antergos live disk is booting the wrong kernel too!

**Comment by sweisman** [comment]
@cawilliamson I will add LightDM to the boot.

Most things work as expected. The program cmst (Connman System Tray) does not. The GUI is bloated way out of proportion. This is a Qt app. Any suggestions?

Does your config reduce the max. clock?

**Comment by sweisman** [comment]
How do I completely remove the bootstrap kernel? Just the files in /boot and /lib/modules? Others?

Pulseaudio pegs the CPU.

**Comment by sweisman** [comment]
Booted a bootstrapped Ubuntu (from the latest commit). Boot sequence switches to correct orientation, X takes FOREVER to boot, and it is oriented wrong.

**Comment by sweisman** [comment]
The options for the latest bootstrapped Arch ISO are:

initrd=\EFI\archiso\intel_ucode.img initrd=\EFI\archiso\archiso.img archisobasedir=arch archisolabel=ARCH_201708

Still get the same 4.12.3 kernel on boot.

The /boot dir does not have vmlinuz-linux. It does have vmlinuz-4.13.0-rc0-bootstrap. It's size is 7468816, dated 4 August.

**Comment by cawilliamson** [comment]
I've figured this one out and I'm working on a fix for it.

In short - the EFI image ALSO contains a second kernel and initrd image... I have absolutely no idea why Arch has done this but never mind - should be fixed shortly.

**Comment by cawilliamson** [comment]
I've added a fix for the kernel being loaded and now the correct one is loaded over EFI so the GPD Pocket loads with the correct kernel - yay! Now, however, I need to get the correct /lib/modules to be loaded since currently /lib is at /lib_1 and a new /lib is in its place. 👎 

Should have this one wrapped up shortly.

**Comment by cawilliamson** [comment]
This is now COMPLETELY fixed - woooooo!!!!!! 👍 

In order to run this temporarily (this will soon be rolled in to `bootstrap-iso.sh`) you can run the following:

```
git pull && ansible-playbook iso.yml -e "iso=../archlinux-2017.08.01-x86_64.iso"
```

I need to get debian, fedora and gentoo working with this ansible-based iso bootstrapping, then I'll roll it in to bootstrap-iso.sh

Cheers all!
