### ISSUE TITLE
Rebuild manjaro-i3-17.0.2-stable-x86_64.iso failed.

### ISSUE THREAD

**Issue by LeosDing** [cawilliamson/ansible-gpdpocket#15]
# chmod +x bootstrap-iso.sh
# sudo ./bootstrap-iso.sh manjaro-i3-17.0.2-stable-x86_64.iso
......
TASK [audio : copy audio config files to device] *********************************************************************************
changed: [localhost] => (item=files/chtrt5645.conf)
changed: [localhost] => (item=files/HiFi.conf)

TASK [audio : set default sink and source in pulseaudio] *************************************************************************
failed: [localhost] (item={u'value': u'alsa_card.platform-cht-bsw-rt5645 HiFi', u'key': u'set-card-profile'}) => {"failed": true, "item": {"key": "set-card-profile", "value": "alsa_card.platform-cht-bsw-rt5645 HiFi"}, "msg": "Destination /etc/pulse/default.pa does not exist !", "rc": 257}
failed: [localhost] (item={u'value': u'alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink', u'key': u'set-default-sink'}) => {"failed": true, "item": {"key": "set-default-sink", "value": "alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink"}, "msg": "Destination /etc/pulse/default.pa does not exist !", "rc": 257}
failed: [localhost] (item={u'value': u'alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink [Out] Speaker', u'key': u'set-sink-port'}) => {"failed": true, "item": {"key": "set-sink-port", "value": "alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink [Out] Speaker"}, "msg": "Destination /etc/pulse/default.pa does not exist !", "rc": 257}
	to retry, use: --limit @/usr/src/ansible-gpdpocket/site.retry

PLAY RECAP ***********************************************************************************************************************
localhost                  : ok=10   changed=4    unreachable=0    failed=1

**Comment by cawilliamson** [comment]
Fix added - please re-download and try again. :)

**Comment by LeosDing** [comment]
@cawilliamson  
new failed.
`
RUNNING HANDLER [boot : update boot] *********************************************************************************************
changed: [localhost]

RUNNING HANDLER [power : enable gpd-fan] *****************************************************************************************
changed: [localhost]

RUNNING HANDLER [power : enable thermal services] ********************************************************************************
failed: [localhost] (item=thermald) => {"failed": true, "item": "thermald", "msg": "Unable to enable service thermald: Failed to enable unit, file thermald.service: No such file or directory.\n"}
changed: [localhost] => (item=tlp)

RUNNING HANDLER [xorg : enable gpd-rotate] ***************************************************************************************

RUNNING HANDLER [xorg : update dconf] ********************************************************************************************
	to retry, use: --limit @/usr/src/ansible-gpdpocket/site.retry

PLAY RECAP ***********************************************************************************************************************
localhost                  : ok=31   changed=20   unreachable=0    failed=1   

`

**Comment by cawilliamson** [comment]
Ahh wait - manjaro isn't in the distro list.

I've now added it - could you try now and let me know if this resolves the issue? :)

**Comment by LeosDing** [comment]
I am rebuilding new manjaro-i3 iso. If I find new issue, I will report again as soon as possible.

**Comment by cawilliamson** [comment]
Awesome - will close this one off for now and feel free to just re-open it if needed. :)
