### ISSUE TITLE
bash bootstrap-iso.sh ../linuxmint-18.2-cinnamon-64bit.iso fails

### ISSUE THREAD

**Issue by mattiluo** [cawilliamson/ansible-gpdpocket#16]
Trying to bootstrap iso in Ubuntu 16.04 running in Virtualbox fails with

TASK [power : set tlp options] *************************************************
failed: [localhost] (item={u'value': u'mmcblk0', u'key': u'DISK_DEVICES'}) => {"failed": true, "item": {"key": "DISK_DEVICES", "value": "mmcblk0"}, "msg": "Destination /etc/default/tlp does not exist !", "rc": 257}
failed: [localhost] (item={u'value': u'sfq', u'key': u'DISK_IOSCHED'}) => {"failed": true, "item": {"key": "DISK_IOSCHED", "value": "sfq"}, "msg": "Destination /etc/default/tlp does not exist !", "rc": 257}

**Comment by cawilliamson** [comment]
I've just added fix for this - linux mint wasn't in the distro list, it is now!

Please rebuild and let me know if this works (or not.) :)

**Comment by mattiluo** [comment]
Oh, my bad.

Now it successfully built the ISO, thanks!

**Comment by cawilliamson** [comment]
Woo - sounds good! :)
