### ISSUE TITLE
Unable to find a medium containing a live file system

### ISSUE THREAD

**Issue by fishkopf** [cawilliamson/ansible-gpdpocket#19]
Hey, 
I have an issue with Ubuntu (16.04.3 & 17.04 & Linux Mint Cinnamon).
I can bootstrap the system, no problem but when i try to boot from USB stick, i get:

>[...] 
> Begin: Running /scripts/init-premount ... done.
> Begin: Mounting root file system ... [X.XXXXX] EXT4-fs (mmblk0p5): mounted filesystem with oredered data mode. Opts: (null)
> [ XX.XXXXX] random: crng init done
>
> BusyBox v.1.22.1 (Ubuntu 1:1.22.0-15ubuntu1) build-in shell (ash)
> Enter 'help' for a list of build in commands
>
> (initramfs) Unable to find a medium containing a live file system`

First i thought i did something wrong writing the file to disk, but apparently it works with a arch iso. 
I also tried multiple Usb-Drives, so i doubt its a problem of the writing process but a problem with the scripts, even though I am not excluding the possibility yet.

I used Ubuntu as well as Debian to build the iso, and i build it several times, no luck. 
Any suggestions?

PS: the output could contain typos, obviously had to copy it by hand.

**Comment by cawilliamson** [comment]
If you boot using a livecd you will be able to get to the livecd environment but sadly the debian-installer isn't currently working. I am working on this and will update once this is resolved - you can track my progress at ticket #13 for that. :)

Thanks!

**Comment by fishkopf** [comment]
Sorry but i have to reopen this, the problem persists.
The problem doesn't seem to be related to the installer, i can not boot into the live system either.

Still get the message: Unable to find a medium containing a live file system.
Could it be related to the BIOS i am using? which one are you using?

**Comment by cawilliamson** [comment]
Just to confirm - you are using a full desktop install image right? Not a netboot one?

For example - this should work: http://releases.ubuntu.com/16.04.3/ubuntu-16.04.3-desktop-amd64.iso

**Comment by fishkopf** [comment]
I tried exactly this one, as well as the 17.04 version and Linux Mint Cinnamon all 64bit, all the same issue. Tried 3 different USB sticks so far just to rule that out. 
I tried the Archlinux image; there where no issues (didn't go through with the installation but i got into the regular command line).

I am happy to provide you with any further information, but i don't what else to try atm. ;)

**Comment by cawilliamson** [comment]
I've figured out what the problem was - give me a couple of mins - just testing a fix now.

**Comment by cawilliamson** [comment]
Yup - should be fixed now.

Please give the latest code a shot and let me know if the issue persists. :)

**Comment by fishkopf** [comment]
Wow awesome, it works now. 
Incredible work you are doing here.
Thanks :)

**Comment by icebal** [comment]
I am also getting this with the 17.04 full desktop image and the latest git pull. This is happening in both the live boot entry, as well as just the installer entry
