### ISSUE TITLE
Issues installing Kali Linux

### ISSUE THREAD

**Issue by cawilliamson** [cawilliamson/ansible-gpdpocket#2]
Copied from reddit:

> Oh boy, I'm having a lot of trouble. I'm trying to install Kali Linux, and after installing from a fresh ISO, it won't even boot into the desktop. Well, it sorta does, if you count a black screen that accepts login credentials and control alt delete to turn it back off. How can I do the re spin on an ISO before I install it?

**Comment by cawilliamson** [comment]
Could you possibly try installing again using a "bootstrapped" iso?

You can find instructions at:

https://www.reddit.com/r/GPDPocket/comments/6rszbo/project_linux_installer_for_gpd_pocket/

**Comment by antichamber** [comment]
(That was my post by the way) What happened is that I was just installing a non respun to the pocket, and trying to run your script from there. I've gotten much further now, I have everything set up on a Linux machine, but I have a new problem. When trying to run build.sh, I get an error saying my ISO must be an Ubuntu(or Ubuntu flavor) or neon desktop ISO

**Comment by antichamber** [comment]
I just realized you posted a new version, I'll try that

**Comment by cawilliamson** [comment]
Closing this in favour of your other bug report.

**Comment by nahci13** [comment]
After install and boot still black screen with iso Image created with *bootstrap-iso.sh*, like unpatched iso image.

**Comment by cawilliamson** [comment]
I'm looking in this now and will report back shortly.

I think I may have resolved the issue but I'll test in a VM and report back.

**Comment by cawilliamson** [comment]
Hi again - just checking this and I'm wondering how you actually got the installer to start in the first place on Kali?

Using the "install" option it looks like it's missing an option it perhaps needs to actually start up the installer. Did you find this too or did the installer start properly?

**Comment by cawilliamson** [comment]
I've raised ticket #13 in regards to the above - not sure how you're installing my image (I suspect you're *not* actually using my image. I don't use anything called build.sh - that's from the respin repo - not mine.)

**Comment by nahci13** [comment]
Hello, Until yesterday I had no problem to make usb bootable and get or run *installer* option in *grub2*.
Now I tried to make new patched image to make new usb bootable but iso file apparently isn't correct bootable.

**Comment by cawilliamson** [comment]
> isn't correct bootable?

Can you elaborate? Not entirely sure what you mean.

**Comment by nahci13** [comment]
this is compare partition between main kali image __(/dev/sdc)__  with patched kali image __(/dev/sdd)__

```
Disk /dev/sdc: 14.9 GiB, 16008609792 bytes, 31266816 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: xxxxxxxxxx

Device     Boot   Start     End Sectors  Size Id Type
/dev/sdc1  *         64 5565119 5565056  2.7G 17 Hidden HPFS/NTFS
/dev/sdc2       5565120 5566527    1408  704K  1 FAT12


Disk /dev/sdd: 7.2 GiB, 7731314688 bytes, 15100224 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: xxxxxxxxxx

Device     Boot Start     End Sectors  Size Id Type
/dev/sdd1  *        0 6678143 6678144  3.2G  0 Empty
/dev/sdd2        1544    2183     640  320K ef EFI (FAT-12/16/32)
```

in new patched image we losing data partition __(/dev/sdd1)__  .

**Comment by cawilliamson** [comment]
I have made huge changes to the debian/ubuntu/kali install process which should allow the system to both boot properly (in my testing) and install properly from the patched ISO.

As such - I'm going to close this one for now and will re-open if necessary but I suspect this one is thoroughly resolved (at least, I very much hope so!)
