### ISSUE TITLE
Fedora 26 fail to install

### ISSUE THREAD

**Issue by msaong** [cawilliamson/ansible-gpdpocket#20]
Bootstrap ISO, and boot with U-DISK, it will show "Failed to start Load Kernel Modules" and halt.

The Fedora ISO is Fedora-Workstation-Live-x86_64-26-1.5.ISO

**Comment by cawilliamson** [comment]
The initial bug is now fixed - sorry about that!

Now it's complaining about checksums so let me figure this one out and then get back to you shortly.

**Comment by msaong** [comment]
Thanks, i will try again.

I try to bootstrap Installed System ,and it can't finish also.
It said:
TASK [common : install update script] *******************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "6a266f92d324a5af4ac9eb9ee0bb096cf411238d", "failed": true, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}

**Comment by cawilliamson** [comment]
Nah it doesn't need that in the bash - needs to be added to ansible which is now there.

I'm testing still at my side though - it does boot but then either complains about checksums (unless I use the other boot option which skips those) or it complains that it can't start various services. I wonder if selinux is the culprit.

**Comment by cawilliamson** [comment]
Ok - I believe this should now be fixed but for now - please use the "Start Fedora-Workstation-Live 26" instead of "Test this media & start...." since the "test this media" part will fail currently. I'll create a separate issue to resolve this as time permits but for now - you should be able to get to the installer at least!
