### ISSUE TITLE
gpd-update wait too long and spend too much time

### ISSUE THREAD

**Issue by diandengs** [cawilliamson/ansible-gpdpocket#23]
When I gpd-update ,these two steps waiting for a very long time, update a system should not wait for so long, even if it takes so long, should provide a progress bar to view the progress, or can not know whether the script has been stuck, can not know how much time , In this case, the user can interrupt the script can not know, it is recommended to optimize gpd-update.

TASK [boot : fetch latest jwrdegoede kernel sources (this may take a while)] *************************************************************************************
changed: [localhost]

TASK [boot : build new kernel (this may take a while)] ***********************************************************************************************************
changed: [localhost]

**Comment by cawilliamson** [comment]
The step you're waiting for is the one which pulls a full set of source code from a git repository for an entire kernel, then compiles it entirely on the GPD Pocket. This process will usually take around 2hrs and there is really nothing I can do about that unless you want older kernels without the latest fixes.

As for the output request - this is an Ansible feature but Ansible doesn't get "stuck" - only one of three things happens:

1.) The build step fails - you will see the script end with a failure.

2.) The system crashes - you may not see this happen but if you want to check if this has occurred (which it shouldn't anymore) you can hit a few characters on the keyboard and they should show up - if there has been a crash - there will be no output.

3.) The build step is still running fine - see point above on how to check this.

I agree that I would like to see Ansible add a little spinner or something to let you know it's still alive and I will raise this with them but I want to be very clear - there is no "optimize gpd-update" work to be done here - compiling a kernel is a tough job and you're asking a very small computer to perform it - it will take a while (hence the title of the task!)

**Comment by diandengs** [comment]
I mean this is the case, I hope this update becomes transparent, if you can download the kernel and edit the kernel required time to calculate and display on the terminal, then it is better. Because i and some of my friends, they often wait for the interface to wait too long and ctrl + c interrupt script, because we can not know, how much time does it take?

**Comment by cawilliamson** [comment]
Then you need to learn some patience.

I am not intending to perform any changes to address this since it is not an issue.

**Comment by diandengs** [comment]
Thank you for your patience reply，I would also like to ask, I see some documents on github are updated, such as fixing a BUG, i re-run gpd-update will be re-compiled and wait a few hours?

**Comment by cawilliamson** [comment]
Building a kernel can take a while - the title says "this can take a while".

I really don't know what more you want me to do. If you don't like waiting - don't update. No problem.
