### ISSUE TITLE
Fedora 26 fails to boot to installer

### ISSUE THREAD

**Issue by msaong** [cawilliamson/ansible-gpdpocket#24]
I make the iso again and boot with U-Disk, install via "Start Fedora-Workstation-Live 26", it halt and show below
![picture_20170809172806](https://user-images.githubusercontent.com/25732857/29114876-2bcc7e0a-7d28-11e7-88c5-a444e14f618f.jpg)

**Comment by cawilliamson** [comment]
Please try creating your ISO again - I added some fixes this morning and I am not seeing this issue at my end at this point.

**Comment by msaong** [comment]
OK, i try again. But in fact my ISO is new build.

**Comment by cawilliamson** [comment]
Ok - if your issue persists let me know and I'll have a look when I get home from work (8hrs or so.)

Thanks

**Comment by cawilliamson** [comment]
@msaong - any news on this from your side? :)

**Comment by msaong** [comment]
@cawilliamson 
I try to build the ISO again via new download Fedora-Workstation-Live-x86_64-26-1.5.ISO, new github project clone and new build. The build eniverment is VMware host with new install Ubuntu 16.04 OS. All new.

I get bootstrap.iso with information below

size: 2518515712 byte
MD5: 9F32D5398DEE5CBB9CA28D74371E68FE
SHA1: F451F5F1899B86BE3302F4C51806188F6A432EE5
CRC32: 255D6C72

flash second iso to U-disk via DD, it can't boot into install gui and halt with "started LVM2 PV scan on device 179:3"
and i also try to flash the iso via FedoraMediaWriter-win32-4.1.0, nothing different, halt too.

**Comment by cawilliamson** [comment]
Just wanted to update you on this - I haven't forgotten about it.

This is a bit of a tricky one to fix but what I'm working on is #32 - this will enable me to move all distro specific work to an individual ansible playbook (in other words - I can create a custom "script" just for fedora livecd building.)

Once this is in place I should be a lot clearer on what's going wrong and where. At the minute I'm trying to do everything with one script and it's a less than perfect approach!

**Comment by msaong** [comment]
Thanks, it dosen't matter.

I am trying to adjuct the Fedora  draw on the experience of you ansible.

I also try the bootstrap-system.sh in Centos, it result with many issues, I am trying to fix this(Centos). CentOS ansible must use special playbook, because it come without dnf but only yum, some package is different.

I already fork your project, I think I can help to improve the Centos playbook.

**Comment by cawilliamson** [comment]
You may want to hold off on that - I'm changing the bootstrap-iso code to all be in Ansible where possible and am likely to release this later today which should simplify the process significantly.

**Comment by cawilliamson** [comment]
The CentOS and RedHat support is poor at best though btw - the aim was to support Fedora first, then work on the others.

**Comment by msaong** [comment]
cawilliamson , can i start new fedora try now?

**Comment by cawilliamson** [comment]
@msaong Sorry - what are you asking here? Fedora install is still not fixed at this point but the new method of bootstrapping an ISO is much better.

Feel free to fork the repo and try to fix support if you're feeling confident you can help. 👍
