### ISSUE TITLE
Missing symbolic link for DNS (/etc/resolv.conf) in Mint 18.2.

### ISSUE THREAD

**Issue by vicentegomez** [cawilliamson/ansible-gpdpocket#27]
On a clean installation of a bootstrapped Mint 18.2 the DNS resolution is broken.

resolvconf.service logs warn: "/etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf"

Creating the symbolic link fixes DNS resolution.

**Comment by cawilliamson** [comment]
I believe this is now fixed - sorry about that!

Let me know if the issue persists.
