### ISSUE TITLE
bootstrap-iso: unsquashfs fails when processing Debian ISO

### ISSUE THREAD

**Issue by kgbvax** [cawilliamson/ansible-gpdpocket#29]
Running under Debian9, when processing debian-9.1.0-amd64-netinst.iso results in this error:

> + grep -q ' boot=' /var/tmp/bootstrap-iso/isolinux/rqgtk.cfg
>+ sed -i 's, quiet, boot=live selinux=0,g' /var/tmp/bootstrap-iso/isolinux/rqgtk.cfg
>+ sed -i 's, splash,,g' /var/tmp/bootstrap-iso/isolinux/rqgtk.cfg
>+ read -r BOOT_CONFIG
>+ unsquashfs -d /var/tmp/bootstrap-iso/squashfs/ -f
>SYNTAX: unsquashfs [options] filesystem [directories or files to extract]
>	-v[ersion]		print version, licence and copyright information
>	-d[est] <pathname>	unsquash to <pathname>, default "squashfs-root"
>	-n[o-progress]		don't display the progress bar
>	-no[-xattrs]		don't extract xattrs in file system
>	-x[attrs]		extract xattrs in file system (default)
>	-u[ser-xattrs]		only extract user xattrs in file system.
>				Enables extracting xattrs
>	-p[rocessors] <number>	use <number> processors.  By default will use
>				number of processors available
>	-i[nfo]			print files as they are unsquashed
>	-li[nfo]		print files as they are unsquashed with file
>				attributes (like ls -l output)
>	-l[s]			list filesystem, but don't unsquash
>	-ll[s]			list filesystem with file attributes (like
>				ls -l output), but don't unsquash
>	-f[orce]		if file already exists then overwrite
>	-s[tat]			display filesystem superblock information
>	-e[f] <extract file>	list of directories or files to extract.
>				One per line
>	-da[ta-queue] <size>	Set data queue to <size> Mbytes.  Default 256
>				Mbytes
>	-fr[ag-queue] <size>	Set fragment queue to <size> Mbytes.  Default
>				256 Mbytes
>	-r[egex]		treat extract names as POSIX regular expressions
>				rather than use the default shell wildcard
>				expansion (globbing)
>
>Decompressors available:
>	gzip
>	lzma
>	lzo
>	lz4
>	xz

There seems to be an argument missing to unsquashfs after the -f

**Comment by cawilliamson** [comment]
netinst images won't work because there isn't a system image to patch. You need to download a full installer.

**Comment by cawilliamson** [comment]
Change merged - closing this one. Apologies for the confusion. :)
