### ISSUE TITLE
gpd-update hangs on waiting for internet connection

### ISSUE THREAD

**Issue by sweisman** [cawilliamson/ansible-gpdpocket#30]
This function waits for pool.ntp.org. I live in Israel and for some reason, this specific domain is either unreachable or unpingable. I suggest using something else to check this.

**Comment by kgbvax** [comment]
pool.ntp.org is the global NTP cluster address, seems a fine choice for me.

**Comment by cawilliamson** [comment]
I'll patch that shortly - thanks!

**Comment by cawilliamson** [comment]
A fix has now been added to switch this to 8.8.8.8 (google public dns.)

Please reopen and let me know if you have any further problems. :)
