### ISSUE TITLE
bootstrap-iso.sh fails with "Cannot write all bytes to disk filesystem path"

### ISSUE THREAD

**Issue by anomalouscowherd** [cawilliamson/ansible-gpdpocket#35]
It looks like the disk is filling up.

bash bootstrap-iso.sh ../../../Desktop/ubuntu-17.04-desktop-amd64.iso

xorriso : FAILURE : Cannot write all bytes to disk filesystem path '/var/tmp/bootstrap-iso/casper/filesystem.squashfs' : No such file or directory
xorriso : FAILURE : Cannot restore regular file to disk filesystem: '/casper/filesystem.squashfs'
xorriso : SORRY : Restoring failed:  '/casper/filesystem.squashfs' = '/var/tmp/bootstrap-iso/casper/filesystem.squashfs'
xorriso : UPDATE : 263 files restored ( 442.2m) in 15 seconds = 22.9xD
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'

bsmall@debian:~/Documents/ubuntu-iso/ansible-gpdpocket$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            488M     0  488M   0% /dev
tmpfs           100M  3.2M   97M   4% /run
/dev/sda1       1.9G  1.7G   75M  96% /
tmpfs           499M     0  499M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           499M     0  499M   0% /sys/fs/cgroup
/dev/sda7       234M  2.1M  215M   1% /tmp
/dev/sda8       3.8G  1.7G  2.0G  46% /home
/dev/sda5       936M  920M     0 100% /var
tmpfs           100M  4.0K  100M   1% /run/user/111
tmpfs           100M   12K  100M   1% /run/user/1000

**Comment by cawilliamson** [comment]
You need to increase the partition size of your /var partition.

I'm really not sure what you expect me to do about this? :|

**Comment by anomalouscowherd** [comment]
The script needs to check for sufficient space before it tried to write a ~1.5Gb file.  In addition if you fill up my root partition my machine will not run. 

Since this is the default setup for a minimal xfwm desktop system on virtualbox, most of your users will have this problem.

Please don't close issues without input from the users.

Thanks for your efforts.

**Comment by cawilliamson** [comment]
The problem is - a Ubuntu CD needs about 1.5GB.
An Arch CD needs about 600MB.
A Gentoo LiveDVD needs about 5GB.

Where do you draw the line?

I've closed this as WONTFIX because ultimately - it's not something which concerns me. You build an ISO once or twice total generally - I don't want a million and one different checks for edge cases like this. Sorry!

**Comment by Herst** [comment]
@anomalouscowherd: If can figure out some way to determine the size usage beforehand, feel free to give some pointers, maybe even make a PR.
