### ISSUE TITLE
Ubuntu 17.04 No battery readout

### ISSUE THREAD

**Issue by wallace11** [cawilliamson/ansible-gpdpocket#36]
This one is simple? I guess. 
I just moved from the old ansible to the new one. 
ansible-update-->reboot-->select different old kernel in grub menu-->gpd-update-->update-grub-->reboot-->select new kernel
My battery constantly shows 50% (confirmed it's not a hardware problem by booting to Windows).

**Comment by cawilliamson** [comment]
This is an easy one but it's a known issue. The Ubuntu bios doesn't show battery life on Linux. Hans is aware and is working on it.

**Comment by wallace11** [comment]
I had no idea it's a known issue. 
May I ask where can I find Hans's repo?

**Comment by Herst** [comment]
@wallace11 You can find it at <https://github.com/jwrdegoede/linux-sunxi>. Please be aware that he rebases the repository quite often and new and old patches get thrown around in no order relating to their date.

**Comment by cawilliamson** [comment]
@Herst Cheers 👍 

@wallace11 You're absolutely right though - poor show on my part - I'll add it to the README. I should also point out that ALL other BIOS versions work and show battery info properly - just not the Ubuntu (unlocked) one. The latest one (sadly locked) is what I'm running until Hans has patched this stuff. He's having to work around a crappy hack GPD has put in place though. Very frustrating kit to work with this GPD stuff!
