### ISSUE TITLE
The file bootstrap-iso.sh can not execute completely.

### ISSUE THREAD

**Issue by LeosDing** [cawilliamson/ansible-gpdpocket#40]
When script runing next line:
`102   cp -fL ${TMPDIR}/squashfs/boot/vmlinuz-*-bootstrap ${KERNEL_PATH}`
There has tips:
`cp: '/var/tmp/bootstrap-iso/squashfs/boot/initrd.img-4.13.0-rc0-bootstrap' and '/var/tmp/bootstrap-iso/squashfs/boot/initrd.img-4.13.0-rc0-bootstrap' are the same file`

And bootstrap-iso.sh is exit.

**Comment by cawilliamson** [comment]
Hey - which ISO is this happening on?

**Comment by cawilliamson** [comment]
I've managed to track this one down and added a fix.

Let me know if you have any further problems. :)

**Comment by LeosDing** [comment]
@cawilliamson manjaro-i3-17.0.2-stable-x86_64.iso
