### ISSUE TITLE
Add BIOS updating support

### ISSUE THREAD

**Issue by cawilliamson** [cawilliamson/ansible-gpdpocket#44]
The aim here is to add support for updating BIOS to the latest unlocked version.

This would be an OPTIONAL component and would *NOT* be done automatically without a specific flag being used - the reason for this being that updating the bios is always risky and isn't something you will want to do without being aware of the risks.

**Comment by Herst** [comment]
The latest unlocked version is the one with the battery charging bug though?

BTW, there is a code snipped flying around where a backup is created beforehand, I am not sure this might be necessary as from what I understand `flashrom` might be already doing that implicitly.

And yes, it's a good idea to not do it automatically, the user should only do it if after confirming that the battery is fully charged.

**Comment by cawilliamson** [comment]
The battery bug is patched now - haven't tested yet but Hans reports he has added a patch.

**Comment by Herst** [comment]
I can confirm that the battery charge display works now.

**Comment by cawilliamson** [comment]
I've decided against this one - just too risky and I don't want to be responsible for bricking anyones GPD Pocket.
