### ISSUE TITLE
Not network card driver

### ISSUE THREAD

**Issue by LeosDing** [cawilliamson/ansible-gpdpocket#45]
When I start manjaro (rebuild manjaro-i3-17.0.2-stable-x86_64.iso ) from usb device, could not connect to network. 
If i run ifconfig, only show lo device,  it's looks like no network card driver.

PS.
I add some isolinux files and change bootstrap-iso.sh, the new bootstrap.iso can starting as normally.
such as: 
```
--------------------------------------------------------------------------------------------------------------
--- bootstrap-iso.sh_git	2017-08-12 20:03:47.608436665 +0800
+++ bootstrap-iso.sh	2017-08-12 19:24:53.906355630 +0800
@@ -122,6 +122,7 @@
   find ${TMPDIR} -type f -print0 | xargs -0 md5sum | grep -v "\./md5sum.txt" > ${TMPDIR}/md5sum.txt
 fi
 
+tar xvzf ./isolinux.tar.gz -C ${TMPDIR}
 # re-assemble iso
 dd if="${1}" bs=512 count=1 of=${TMPDIR}/isolinux/isohdpfx.bin
 ISO_LABEL=$(blkid -o value -s LABEL "${1}")
```

**Comment by fishkopf** [comment]
I had a similar problem just a minute ago,
could you check if you can find a file called: 

> brcmfmac4356-pcie.txt
inside of:
>/lib/firmware/brcm 
?

**Comment by LeosDing** [comment]
@fishkopf  not found brcmfmac4356-pcie.txt, and no /lib/firmware/brcm directory.

**Comment by fishkopf** [comment]
wait you do not have a /lib/firmware/brcm/ directory?
Seems to be Manjaro is putting his stuff somewhere weird... 
is there a folder called brcm in: /usr/lib/firmware/ ?

**Comment by LeosDing** [comment]
@fishkopf  
In Manjaro, no  /lib/firmware/brcm/ directory, but has /usr/lib/firmware/brcm/，in this directory, only find brcmfmac4356-pcie.bin, not found brcmfmac4356-pcie.txt.

**Comment by fishkopf** [comment]
Okay so there seems to be a problem in the script, you can fix it (for now) by manually downloading(and putting it on a usb-drive) brcmfmac4356-pcie.txt from this repo and copy it into that /brcm/ directory.
If I find the time later I'll check if I can find a fix for the scripts, if Chris is not faster than me :)

**Comment by cawilliamson** [comment]
Thanks @fishkopf - I've added a fix for this to auto determine between lib and usr/lib.

Seriously - why do people use this damn distro? 👎

**Comment by cawilliamson** [comment]
@fishkopf - I've fixed the Ubuntu part too by the way.

Forgot to include wifi.yml to the common playbook task list. Sorry about that!
