### ISSUE TITLE
Missing gpdtouch service.

### ISSUE THREAD

**Issue by LeosDing** [cawilliamson/ansible-gpdpocket#46]
Also I start manjaro (rebuild manjaro-i3-17.0.2-stable-x86_64.iso ) from usb device.

The screen touch is wrong operating.

**Comment by cawilliamson** [comment]
I'm closing this one in favour of #41 - it looks like Manjaro is causing a lot of issues.

I'll decide if I continue to support it and if so - I will add fixes to all of these problems.
