### ISSUE TITLE
Debian bootstrap-iso fails

### ISSUE THREAD

**Issue by lpopov** [cawilliamson/ansible-gpdpocket#47]
There are no broadcom drivers in the iso, so it cannot find a destination directory.

Using: https://cdimage.debian.org/debian-cd/9.1.0-live/amd64/iso-hybrid/debian-live-9.1.0-amd64-xfce.iso

Output:
```
TASK [common : copy wifi files] **************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: list object has no element 0\n\nThe error appears to have been in '/usr/src/ansible-gpdpocket/roles/common/tasks/wifi.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: copy wifi files\n  ^ here\n"}
        to retry, use: --limit @/usr/src/ansible-gpdpocket/site.retry
```

**Comment by cawilliamson** [comment]
I have just added a fix for this issue - thanks for bringing it to my attention.

Please post an update if you spot any further problems. :)

**Comment by lpopov** [comment]
There is a missing `/brcm` on line 26, so it copies the files to `/lib/firmware` or `/usr/lib/firmware` instead of `/lib/firmware/brcm` or `/usr/lib/firmware/brcm`.

Thanks for making such a great playbook! :)

**Comment by cawilliamson** [comment]
Oops! Thanks for pointing that out. This is now fixed in the latest commit.

Writing this stuff at 3am isn't a good idea! :(
