### ISSUE TITLE
bootstrap system script missing wifi dir

### ISSUE THREAD

**Issue by snazzybunny** [cawilliamson/ansible-gpdpocket#48]
Reinstalled Ubuntu with the .iso that I already had so I tried the bootstrap system script. Apparently, the wifi directory is missing in the roles folder. NOTE: I did not make my own iso.

`~/ansible-gpdpocket-master$ sudo bash bootstrap-system.sh
[sudo] password for andyph666:
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ stat -c %d:%i /
++ stat -c %d:%i /proc/1/root/.
+ '[' 2050:2 == 2050:2 ']'
+ echo 'enabling wifi...'
enabling wifi...
+ mkdir -p /lib/firmware/brcm
+ cp -f 'roles/wifi/files/brcmfmac4356-pcie.*' /lib/firmware/brcm/
cp: cannot stat 'roles/wifi/files/brcmfmac4356-pcie.*': No such file or directory`

**Comment by cawilliamson** [comment]
I've just now added a fix for this - please let me know if you spot any further problems. :)
