### ISSUE TITLE
bootstrap-iso doesn't report when file doesn't exist

### ISSUE THREAD

**Issue by antichamber** [cawilliamson/ansible-gpdpocket#5]

**Comment by cawilliamson** [comment]
Me and Kali Linux are REALLY starting to fall out! :(

Looking in to this now and will report back shortly.

**Comment by cawilliamson** [comment]
Changes:
- [FIXED] Due to a slightly odd naming convention on the initrd image - my script wasn't finding it.
- [FIXED] No kali support on the ansible repo - forced to trusty which should be used universally on debian based repos from this point.
- [FIXED] dirmngr isnt installed by default on Kali - needed for apt-key fetching.
- [FIXED] Kali wasn't a supported distribution on the ansible playbooks
- [FIXED] Grub wasn't installed by default
- [FIXED] casper was being installed - not required on Debian & Kali
- [FIXED] Kali doesnt contain /etc/default/grub by default - created automatically now.
- [FIXED] Kali ships with an odd update-initramfs binary which accepts EITHER -c or -u depending on if the file already exists - yuck! -c will be used and -u will be failed over to if -c fails.

Looks like the ISO bootstrapping works properly with these fixes in place - let me know if you have any further problems with this.

I'll test the resulting ISO shortly and report back.

**Comment by cawilliamson** [comment]
I'm marking this as closed now since the bootstrap-iso does now produce an ISO.

There are potentially further problems preventing a Kali install at this point but I will discuss those in bug report:

https://github.com/cawilliamson/ansible-gpdpocket/issues/4

Thanks

**Comment by cawilliamson** [comment]
Looks like with my changes whilst an ISO is created - it sadly doesn't boot.

I'm trying to figure out what the Kali equivalent of "casper" is.

**Comment by cawilliamson** [comment]
It looks like Debian and Kali both use: `live-boot` and `live-boot-initramfs-tools` to provide a livecd environment. I have now added a fix for this to be included properly but even with the fix in place a boot=live used as a boot option I now get:

`cat: can't open '/sys/block/loop*/size': no such file or directory
sh: bad number

I suspect another boot parameter should be used to tell the livecd where the image it needs to load lives. Strange that the stock kali installer doesn't require this parameter - must be built in somehow.

**Comment by cawilliamson** [comment]
Managed to figure out the problem above - missing module (`overlay`.)

I've just added fixes to add `boot=live` to the kernel boot options (and removed `quiet` and `splash` because they're not needed and cab, in some cases, cause problems.)

**Comment by cawilliamson** [comment]
Actually nope - haven't fixed it.

I have now though - essentially came down to loop not being loaded with `options loop max_loop=8` so no default loop devices were created. I have now changed this and the iso seems to boot properly.

**Comment by cawilliamson** [comment]
This is now completely fixed - install CD boots properly and works perfectly.

I haven't attempted an install so your mileage there may vary but I'll close this one for now.

**Comment by nahci13** [comment]
I get this error with Kali Linux Weekly iso.
```
..
...
+ read -r BOOT_CONFIG
+ sed -i 's, splash,,g' /var/tmp/bootstrap-iso/boot/grub/grub.cfg
+ sed -i 's, quiet, boot=live,g' /var/tmp/bootstrap-iso/boot/grub/grub.cfg
+ read -r BOOT_CONFIG
+ sed -i 's, splash,,g' /var/tmp/bootstrap-iso/boot/grub/i386-efi/grub.cfg
+ sed -i 's, quiet, boot=live,g' /var/tmp/bootstrap-iso/boot/grub/i386-efi/grub.cfg
+ read -r BOOT_CONFIG
+ unsquashfs -d /var/tmp/bootstrap-iso/squashfs/ -f /var/tmp/bootstrap-iso/squashfs/usr/share/doc/dosfstools/README.mkdosfs
Can't find a SQUASHFS superblock on /var/tmp/bootstrap-iso/squashfs/usr/share/doc/dosfstools/README.mkdosfs

```
file *README.mkdosfs* exists.

**Comment by cawilliamson** [comment]
They make this thing WEEKLY?! 👎 

It's been a nightmare getting it working in the first place and now they can break it every week?! :P

Should be working now though - added a fix for the initrd detection and also the initrd creation (was picking up the wrong kernel version to build the initrd image for.)

**Comment by nahci13** [comment]
Yes it work, but new error:

```
..
...
+ INITRD_PATH=
+ cp -L /var/tmp/bootstrap-iso/squashfs/boot/initrd.img-4.13.0-rc0-bootstrap
cp: missing destination file operand after '/var/tmp/bootstrap-iso/squashfs/boot/initrd.img-4.13.0-rc0-bootstrap'
Try 'cp --help' for more information.
```

**Comment by cawilliamson** [comment]
Can you provide me a link to the iso youre using here?

**Comment by nahci13** [comment]
Kali Linux Weekly Builds:
```
https://cdimage.kali.org/kali-images/kali-weekly/
```
I use *kali-linux-2017-W32-amd64.iso*.

**Comment by cawilliamson** [comment]
I've just added a few fixes which should resolve this issue.

Looks like it was trying to copy the initrd image when there was nowhere to copy it to (i.e. it wasn't needed.) I've fixed the handling for this now so it should no longer happen in future.

Could you try again and let me know if the issue persists?

**Comment by nahci13** [comment]
Works, Thank you!

**Comment by cawilliamson** [comment]
Glad to hear it! Enjoy! :)

**Comment by nahci13** [comment]
Hello
I get new error:
```
..
...
+ rm -rf /var/tmp/bootstrap-iso/squashfs
+ '[' -f /var/tmp/bootstrap-iso/arch/x86_64/airootfs.md5 ']'
+ '[' -f /var/tmp/bootstrap-iso/md5sum.txt ']'
+ find /var/tmp/bootstrap-iso -type f -print0
+ xargs -0 md5sum
+ grep -v '\./md5sum.txt'
+ dd if=kali-linux-2017-amd64.iso bs=512 count=1 of=/var/tmp/bootstrap-iso/isolinux/isohdpfx.bin
dd: failed to open 'kali-linux-2017-amd64.iso': No such file or directory
```

**Comment by cawilliamson** [comment]
This is simply telling you that the file `kali-linux-2017-amd64.iso` doesn't exist - did you move or delete it during the bootstrap process?

**Comment by nahci13** [comment]
no, file exists in folder ```ansible-gpdpocket``` !

**Comment by cawilliamson** [comment]
Could you move the ISO *out* of the ansible-gpdpocket folder and then try again?

I've also updated the .gitignore to ignore ISO files just in case that was the problem - wont hurt.

**Comment by nahci13** [comment]
no same error!

**Comment by nahci13** [comment]
now I get new error:
```
Copying of file objects from ISO image to disk filesystem is: Enabled
Drive current: -indev 'kali-linux-2017-w32-amd64.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 15.4g free
Extracted from ISO image: file '/'='/var/tmp/bootstrap-iso'
++ find /var/tmp/bootstrap-iso -type f -regex '.*\(grub/.+.cfg\|isolinux/.+.cfg\)'
+ BOOT_CONFIGS=
++ find /var/tmp/bootstrap-iso -type f -iname 'efi*.img' -print -quit
+ EFI_PATH=
++ find /var/tmp/bootstrap-iso -type f -regex '.*\(squashfs\.img\|\.sfs\|\.squashfs\)$' -print -quit
+ SQUASHFS_PATH=
++ find /var/tmp/bootstrap-iso -type f -iname '*vmlinuz*'
+ KERNEL_PATHS=
+ read -r BOOT_CONFIG
+ grep -q ' boot='
+ sed -i 's, quiet, boot=live selinux=0,g'
sed: no input files
```

**Comment by cawilliamson** [comment]
I've now added a check to ensure the file actually exists.

Could you try now and let me know the output.

**Comment by nahci13** [comment]
it is funy:
```
+ rm -rf /var/tmp/bootstrap-iso/squashfs
+ '[' -f /var/tmp/bootstrap-iso/arch/x86_64/airootfs.md5 ']'
+ '[' -f /var/tmp/bootstrap-iso/md5sum.txt ']'
+ find /var/tmp/bootstrap-iso -type f -print0
+ xargs -0 md5sum
+ grep -v '\./md5sum.txt'
+ dd if=kali-linux-2017-W32-amd64.iso bs=512 count=1 of=/var/tmp/bootstrap-iso/isolinux/isohdpfx.bin
dd: failed to open 'kali-linux-2017-W32-amd64.iso': No such file or directory
```
I renamed iso file and removed folder ```/var/temp/bootstrap-iso``` but I get same error!
iso file exists before and after the run ```bootstrap-iso.sh```

**Comment by cawilliamson** [comment]
Cool, glad you managed to get this figured out.

Strange though that you had to give a full path.
