### ISSUE TITLE
"No Bluetooth adapters found" on Ubuntu 17.04

### ISSUE THREAD

**Issue by evilsocket** [cawilliamson/ansible-gpdpocket#51]
Clean install of Ubuntu 17.04 using the latest version of this repo, bluetooth adapter is not detected ( in the README it's listed as one of the things that should be working ).

    Ubuntu 17.04
    Linux gpd 4.13.0-rc0-bootstrap #4 SMP Fri Aug 4 15:00:53 BST 2017 x86_64 x86_64 x86_64 GNU/Linux

![ss](https://user-images.githubusercontent.com/86922/29250970-8afe0fac-804c-11e7-9c34-74272bed8768.png)

**Comment by cawilliamson** [comment]
I believe this is because btusb is not loaded by default - I have now added a fix for this.

Please run `sudo gpd-update` and let me know if the issue persists after a reboot.

**Comment by evilsocket** [comment]
I modprobed it and it's working, fixed, thanks.
