### ISSUE TITLE
slow transition to portrait mode and then to x session

### ISSUE THREAD

**Issue by sweisman** [cawilliamson/ansible-gpdpocket#52]
Two separate but related issues.

I switched to a Display Manager as suggested. It comes up pretty fast, but still oriented wrong. It takes about 5 seconds to automatically reorient. Any hope of making it start immediately in the correct orientation?

Also, the startup for my X session after I login takes between 15-20 seconds. The same X session on my desktop takes about a second. I'm just loading a few small programs and OpenBox. I think you mentioned this as a known problem. Do you know what the issue is?

Otherwise, it all looks really good! I think the only thing I need to do is change the power button behavior to suspend instead of power off.

**Comment by Herst** [comment]
Which distro with which window manager?

**Comment by sweisman** [comment]
Arch. LightDM. OpenBox.

**Comment by sweisman** [comment]
Just discovered that when I log out of the OpenBox session, LightDM is oriented wrong, and stays oriented wrong.

Also, if I comment out /usr/bin/start-pulseaudio-x11 in xprofile, the X session starts nearly instantaneously.

Running PulseAudio Volume Control pegs the CPU and litters dmesg with hundreds of these lines:

[   78.673897]  Audio Port: sst: error code = -22

And, things aren't as good as I thought. Mplayer is not working. Are there any tips on getting this working?

**Comment by cawilliamson** [comment]
Ok so the display orientation does take 5 seconds - this isn't a bug but is to allow slower login managers to rotate properly.

I'm also aware about the logout -> display rotation stuff and will look in to this but I don't believe this is a major problem since in a typical workflow - how often do you log out of your display manager? The way to resolve this is to rotate your desktop within your environment manager but obviously with openbox things aren't quite as simple.

As for the pulseaudio stuff - this is entirely your distro - there is no part of the ansible playbooks which add start-pulseaudio-x11.

**Comment by sweisman** [comment]
Thanks for the info about the Display Manager. Seems reasonable.

Regarding audio and video, have they been tested and used in Arch? Using Gnome? A simple Window Manager like OpenBox?

**Comment by atom-p** [comment]
@sweisman That's the audio bug that I continue to have on Antergos (Arch with Gnome for all intents and purposes). I've tried manually compiling Hans' kernel just in case something was acting up in terms of module installation behind the scenes with the ansible playbook, but that compiled fine and hasn't fixed it.

It's possible to stop the dmesg spam at least through blacklisting the offending module, but this does not fix the sound. Beyond that I haven't had a great deal of luck fixing it. The issue appears to be related to snd-intel-sst-acpi not being able to find the firmware it wants (fw_sst_22a8.bin).

**Comment by cawilliamson** [comment]
@atom-p Have you tried copying the relevant files / folders from /usr/lib/firmware to /lib/firmware to see if that helps?

**Comment by cawilliamson** [comment]
@sweisman Yes - I've used both GNOME and i3 on Arch - no problems with audio other than the crackling sound stuff.

**Comment by atom-p** [comment]
@cawilliamson That did it! Copying the intel directory from /usr/lib/firmware to /lib/firmware has cleared up that issue! Many thanks! (I feel silly missing something so simple for many days, but I've learned a bit more about how kernel compilation and various other things differ from Debian on Arch so it's not a complete loss).

If this is the same problem as @sweisman is having then that same fix should work too.

**Comment by sweisman** [comment]
That worked for me too. The crackling is annoying but tolerable. Hopefully it will be fixed soon.

Also fixed the slow X startup.
