### ISSUE TITLE
gpd-update command not found after installing Antergos with bootstrap

### ISSUE THREAD

**Issue by snazzybunny** [cawilliamson/ansible-gpdpocket#54]
Tried bootstrap iso with antergos and noticed `sudo gpd-update` gives a command not found.

**Comment by Herst** [comment]
Without `sudo` it can't be found either?

**Comment by snazzybunny** [comment]
No it cannot. I just installed Antergos with the bootstrap iso installer and it cant seem to find it. Can't find it with autocomplete either. Should I just try the system bootstrap installer? Right now, my desktop is sideways in Antergos but it seems to boot fine without any issues.

**Comment by snazzybunny** [comment]
Ran the system bootstrap now and it did some changes. Now there is a gpd-update.

**Comment by cawilliamson** [comment]
@snazzybunny That is expected behaviour - since install images are downloaded on-the-fly for arch-based distros there is no way to patch this. You have to install using the bootstrapped ISO, then run bootstrap-system.
