### ISSUE TITLE
After gpd-update, cannot enter login screen - failed to start light display manager

### ISSUE THREAD

**Issue by snazzybunny** [cawilliamson/ansible-gpdpocket#55]
After I run `sudo gpd-update`, I cannot enter the login screen anymore. It says Failed to Start Light Display Manager several times.

**Comment by Herst** [comment]
Which distro?

**Comment by snazzybunny** [comment]
Oops. Antergos and light display manager.

**Comment by cawilliamson** [comment]
Could you try the following command and let me know if it fixes the problem?

`sed -i 's,lightdm-webkit2-greeter,lightdm-gtk-greeter,g' /etc/lightdm/lightdm.conf`

**Comment by snazzybunny** [comment]
It seems to be working now, however, it isn't using the standard display manager. Did you happen install a different one with the ansible playbook?

**Comment by cawilliamson** [comment]
Yes - so to be clear - there was a problem with lightdm-webkit2-greeter in that it wasn't being rotated properly. Switching that to lightdm-gtk-greeter avoids this problem but sadly the config was never patched (this is now fixed.)

Did you notice before that the login screen was not rotated?

**Comment by snazzybunny** [comment]
I attached a screenshot : [screenshot](http://imgur.com/a/R1YMI). Installed xfce4 etc so there doesnt seem to be a way to switch to a different desktop environment like I could with lightdm-webkit2-greeter.

**Comment by cawilliamson** [comment]
A reboot should fix the rotation and the icon in the top right (GNOME icon currently) will let you switch desktop environments. :)

What I meant though was - did lightdm-webkit2-greeter appear rotated properly or was it sideways?

**Comment by snazzybunny** [comment]
lightdm-webkit2-greeter was never rotated properly. There was a time (before bootstrap-iso was implemented) when it tried to rotate it but the desktop was cut off meaning I couldnt see the entire list when I wanted to choose a specific desktop environment. I just rebooted and lightdm-gtk-greeter does not seem to rotate either but at least I can get into the desktop now.

**Comment by cawilliamson** [comment]
Really?

lightdm-gtk-greeter should rotate perfectly - that's exactly what I'm using and it works great!

May be worth checking if gpd-rotate is enabled in systemd:

`systemctl enable gpd-rotate`

**Comment by snazzybunny** [comment]
Yep it works now, thanks! Do you know when the battery indicator will make its way back?

**Comment by cawilliamson** [comment]
It already has since a kernel patch yesterday.

You'll need to sudo gpd-update and it'll take a couple of hours or so to build the new kernel - keep it plugged in and disable sleep before you start the update! ;)
