### ISSUE TITLE
Suggest: check the free disk before created the iso

### ISSUE THREAD

**Issue by msaong** [cawilliamson/ansible-gpdpocket#57]
@cawilliamson i test many times these day, and i notice some failue is because disk is full. I generate a test iso with 10G size and the orginal just take 1.5G.
Maybe you can modificate the shell to check the free space is enoughe?
And, maybe add some notice to the readme?

**Comment by cawilliamson** [comment]
I will modify the README but I'm not adding a check since I'm not sure what the size requirements will be. This is heavily dependent on the size of the ISO in the first place.
