### ISSUE TITLE
Unable to progress past installing intel microcode with gpd-update

### ISSUE THREAD

**Issue by tvjames** [cawilliamson/ansible-gpdpocket#58]
Follow up to #49 

I also encountered the same issue as @evilsocket, but I was able to test the fix suggested by you in https://github.com/cawilliamson/ansible-gpdpocket/issues/49#issuecomment-322548204 which highkighted the root cause.

IIRC my initial install of 17.04 never completed all the installer steps which left things in an inconsistent state. I fixed up an issue with update-initrd missing, then your fix highlighted that apt was still expecting to install packaged from the "cdrom".

All fixed after removing the cdrom source and doing an apt-get update.

Let me also add, thanks for the awesome work in creating and compiling everything needed for good linux support on the pocket.

So root cause, broken initial ubuntu install :)

**Comment by cawilliamson** [comment]
Now THAT is how you submit a bug report! 👍 

That does make sense - so basically I need to patch sources.list during the ubuntu install. Got it.

I'll figure out a way to do that and get this one closed off.

**Comment by tvjames** [comment]
I might try reinstalling ubuntu a few times and see what the cause of the failed install might be too. I'm at a conference this week so won't be able to try it for a few days. 

The other thing I ran into was duplicate sources that were generating warnings in apt commands. They caused a few false fails in the ansible run. I can provide some more info when I'm not in my phone.  

Also, cheers!

**Comment by cawilliamson** [comment]
No worries - now I know where to look I'll spin up a VM with the bootstrapped ISO and see if I can figure out what's causing the cdrom sources issue.

Out of interest - was that the only issue you had with the Ubuntu install? You mentioned it didn't complete.

**Comment by tvjames** [comment]
Yeah pretty much, the install completed, but said that it was unable to do "something" I cant recall. Figured if it rebooted and loaded I'd just see how broken it was. It seemed okay, so I pressed on. 

I built the iso on a mac, using docker for mac. DD'd it to a usb flash drive. The iso process completed successfully as far as i could tell.

**Comment by cawilliamson** [comment]
I've patched this step out temporarily until I have chance to get some more data and figure out the underlying problem here.

Thanks for the info so far @tvjames - greatly appreciated!

**Comment by cawilliamson** [comment]
@tvjames I'm going to close this one for now since I'm confident this is now resolved.

If you do continue to have problems feel free to reopen it but first you may need to try a full Ubuntu reinstall.

If you do have problems starting the Ubuntu installer, however, you can check #82.

Thanks!

**Comment by tvjames** [comment]
I've finally had a chance to revisit this, I pulled the latest, rebuilt the ISO and installed that way but encountered the same issue reported in this comment https://github.com/cawilliamson/ansible-gpdpocket/issues/102#issuecomment-324509252 (being dropped into busybox shell post-install). 

Reinstalled using the unmodified ubuntu 17.04 installer with external display, usb ethernet to internet and installed the playbook successfully that way. 

Apt was complaining about the duplicate source definitions, but that was a quick edit to remove. Everything is working nicely now. 

Cheers!
