### ISSUE TITLE
/usr/src/ansible-gpdpocket already exists and is not an empty directory.

### ISSUE THREAD

**Issue by fishkopf** [cawilliamson/ansible-gpdpocket#6]
Hey,
I am trying to execute the bootstrap.iso,
but when i do i get: fatal: destination path '/usr/src/ansible-gpdpocket' already exists and is not an empty directory.
I am trying to build it on a Debian 9, and the iso i am using is the latex ubuntu iso 16.04.3.

What am I missing?

**Comment by cawilliamson** [comment]
Hi there!

This is rather strange - could you let me know what command you were using when you got this error? (as in the full command string) and also provide as much output as you can?

Thanks

**Comment by fishkopf** [comment]
Sure, the complete command line is:
`sudo sh bootstrap-iso.sh ubuntu-16.04.3-desktop-amd64.iso.
You can find the whole output here:
https://pastebin.com/WhK9kVxm

There are a couple of "#" symbols in there, don't worry about that, that was some printf debugging..

**Comment by cawilliamson** [comment]
I've just added a potential fix for this - can you re-download from this repo and try again? :)

Looks like I wasn't copying the .git subfolder of the repo so the bootstrap script didn't know if it should re-download the full repo or simply update it.

This should now be fixed.

**Comment by fishkopf** [comment]
Hey,
Seems to be fixed,
thanks for your help. Keep up the good work.
