### ISSUE TITLE
Process completes without errors, but no iso is output.

### ISSUE THREAD

**Issue by wermy** [cawilliamson/ansible-gpdpocket#61]
I'm trying to use this on an Ubuntu Mate 16.04 64-bit iso.  I've tried within a vagrant box (Ubuntu 16.04) and an Ubuntu Mate 16.04 virtual machine.  I looked through the logs and don't see any errors.  At the end of the process it says `Your ISO has been successfully created and is at /home/myusername/bootstrap.iso.`  No iso to be found, though.
Any ideas?

**Comment by wermy** [comment]
Never mind, I'm dumb.  Fun fact: if you run the script with sudo (I had to or I got permissions errors in Vagrant), then it dumps the iso in /root/bootstrap.iso, even though it says it outputs to /home/myusername/bootstrap.iso.

**Comment by cawilliamson** [comment]
@wermy Thanks - another issue describing exactly the same problem was reported earlier - just added a fix for that. Thanks! 👍

**Comment by RevoltsRevolution** [comment]
You are a lifesaver. Thank you very much. :)

Still this should be updated for others. Did the same and looked for it everywhere... 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wermy** [comment]
Just curious: why is it outputted into /root in the first place?  Looks like it's hard-coded here: 
https://github.com/cawilliamson/ansible-gpdpocket/blob/master/roles/iso/tasks/main.yml#L271
Would it be better maybe to just output to their home directory?

**Comment by Herst** [comment]
@wermy Good idea (unless someone uses `sudo -H` ;))

**Comment by cawilliamson** [comment]
@wermy Basically because root permissions are needed anyway.

If I write a file owned by root to a /home directory, people will freak out that they can't then delete the file as a regular user - I can almost guarantee it.

I could change this to be fair but it seems like change just for the hell of it instead of actually adding any value.

**Comment by wermy** [comment]
Alright cool, thanks.  Was just curious.  :)

**Comment by cawilliamson** [comment]
No worries! 👍
