### ISSUE TITLE
gpd-update on ubuntu and antergos - no battery icon

### ISSUE THREAD

**Issue by snazzybunny** [cawilliamson/ansible-gpdpocket#62]
Do we need to do anything in order to get the battery icon to display? I've done gpd-update to both Ubuntu and Antergos, however, both OSes do not have the battery indicator.

**Comment by cawilliamson** [comment]
Could you run `uname -a` after rebooting and let me know the results?

There was an issue previously with the battery monitoring not showing when running the unlocked BIOS but this is now resolved.

**Comment by snazzybunny** [comment]
[username@arch-gpd ~]$ uname -a
Linux arch-gpd 4.13.0-rc0-bootstrap #4 SMP Fri Aug 4 15:00:53 BST 2017 x86_64 GNU/Linux

**Comment by snazzybunny** [comment]
Yep I'm on unlocked bios as well.

**Comment by snazzybunny** [comment]
Rebooted with the same results.

**Comment by cawilliamson** [comment]
Did gpd-update run fully?

Basically you're *not* running the latest kernel there. The bootstrap kernel should be replaced - could you try the following?

`ls -l /boot`

**Comment by cawilliamson** [comment]
That's odd - so your kernels have been built and installed but no initrd generated.

Did the ansible playbook error out whilst running gpd-update?

**Comment by snazzybunny** [comment]
nope

**Comment by snazzybunny** [comment]
Is there a way to restart the gpd-update process from scratch?

**Comment by snazzybunny** [comment]
Ubuntu has no entry for rc3 in grub but arch has it in the advanced section in grub.

**Comment by snazzybunny** [comment]
Rc5 seems to crash both arch and ubuntu for me.

**Comment by Sonique** [comment]
Little off-topic. How long battery lasts with Linux, is it comparable to Windows? I use pocket for small admin tasks during the day and its pretty important question for me. 
Thanx

**Comment by cawilliamson** [comment]
@Sonique Very off topic and not being asked in the right place - I would ask this on Reddit. In all honesty I don't know, haven't monitored it too closely.

**Comment by cawilliamson** [comment]
@snazzybunny Could you run gpd-update and post the output to this ticket?

If you need a quick 'N easy way to perform this - install the package `pastebinit`, then run:

`sudo gpd-update | pastebinit`

Then you will get a URL which you can copy the text from on your full sized computer. :)

**Comment by snazzybunny** [comment]
Should I do it for both ubuntu and arch?

**Comment by cawilliamson** [comment]
Which ever is easier - doesn't make much difference. :)

**Comment by snazzybunny** [comment]
https://pastebin.com/ng5Dwpfy

**Comment by cawilliamson** [comment]
Thanks for the log - I see the kernel was built and installed - when you check /boot now do you still not see a -rc5* image for the initrd?

So basically you should see something like:

/boot/initrd.img-hanswhatever-rc5

If you're not seeing an -rc5 initramfs image something is very wrong. The reason you're seeing issues is because you're not running the latest kernel which is VERY strange because you're clearly installing it.

In fact - could you run the following and provide the results?

```
# determine new kernel version
    KERNEL_VERSION=$(ls -t /lib/modules/ |grep 'bootstrap\|jwrdegoede' |head -n 1)
    
    # recreate initramfs image
    if [ -f /usr/sbin/update-initramfs ]; then
      update-initramfs -c -k ${KERNEL_VERSION} || update-initramfs -u -k ${KERNEL_VERSION}
    elif [ -f /usr/bin/dracut ]; then
      dracut -f /boot/initrd.img-${KERNEL_VERSION} ${KERNEL_VERSION}
    elif [ -f /usr/bin/mkinitcpio ]; then
      mkinitcpio -c /etc/mkinitcpio.conf -g /boot/initrd.img-${KERNEL_VERSION} -k ${KERNEL_VERSION} || true
    fi
    
    # Update grub config
    if [ -f /usr/bin/grub-mkconfig ]; then
      grub-mkconfig -o /boot/grub/grub.cfg
    fi
```

**Comment by snazzybunny** [comment]
```
==> Starting build: 4.13.0-rc5-jwrdegoede
  -> Running build hook: [base]
  -> Running build hook: [systemd]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: wd719x
==> ERROR: module not found: `sd_mod'
  -> Running build hook: [btrfs]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initrd.img-4.13.0-rc5-jwrdegoede
==> WARNING: errors were encountered during the build. The image may not be complete.
Generating grub configuration file ...
Found theme: /boot/grub/themes/Antergos-Default/theme.txt
Found Intel Microcode image
Found linux image: /boot/vmlinuz-4.13.0-rc0-bootstrap
Found initrd image: /boot/initrd.img-4.13.0-rc0-bootstrap
Found linux image: /boot/vmlinuz-4.13.0-rc3-jwrdegoede
Found initrd image: /boot/initrd.img-4.13.0-rc3-jwrdegoede
Found linux image: /boot/vmlinuz-4.13.0-rc5-jwrdegoede
Found initrd image: /boot/initrd.img-4.13.0-rc5-jwrdegoede
Found Windows Boot Manager on /dev/mmcblk0p2@/efi/Microsoft/Boot/bootmgfw.efi
Found Ubuntu 16.04.3 LTS (16.04) on /dev/sda2
done
```

**Comment by cawilliamson** [comment]
Ok cool, reboot and then run the following and let me know the output:

`uname -a`

**Comment by snazzybunny** [comment]
Linux arch-gpd 4.13.0-rc0-bootstrap #4 SMP Fri Aug 4 15:00:53 BST 2017 x86_64 GNU/Linux

**Comment by snazzybunny** [comment]
Is it possible to generate a new grub from scratch? I chose rc5 in the advanced configuration and it seemed to boot fine now.

**Comment by cawilliamson** [comment]
Ok - I believe I've now fixed this but need you to run the following:

```
sudo rm -rf /usr/src/linux-jwrdegoede
sudo gpd-update
```

This will force a new kernel build but should THEN remove the old kernels (and associated files) before installing the new one. That should mean there is only then ONE kernel for grub to detect.

It does look like this is working around a bug in an older version of GRUB basically where the ordering is reversed. This is not an issue with the ansible playbooks but it does make sense to remove old kernels before installing new ones.

Let me know how this goes. :)

**Comment by snazzybunny** [comment]
I did it on ubuntu but now I can't use any rc0 or rc3 or rc5. Says error: file /boot/initrd.img-4.13.0-rc5-jwrdegoede is missing :o.

**Comment by cawilliamson** [comment]
I don't... even... how the f...... :(

**Comment by snazzybunny** [comment]
I just finished it on arch. Scared it will do the same lol.

**Comment by snazzybunny** [comment]
Is the iso script working okay? Might just reinstall Ubuntu if it still doesnt work.

**Comment by snazzybunny** [comment]
TASK [iso : extract squashfs image] *************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: list object has no element 0\n\nThe error appears to have been in '/home/ole/ansible-gpdpocket2/roles/iso/tasks/main.yml': line 113, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: extract squashfs image\n  ^ here\n"}

msg: the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: list object has no element 0

The error appears to have been in '/home/ole/ansible-gpdpocket2/roles/iso/tasks/main.yml': line 113, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


Updated the repository and then tried to run the iso script with Antergos and currently getting this.

- name: extract squashfs image
  ^ here


PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=12   changed=4    unreachable=0    failed=1

**Comment by snazzybunny** [comment]
Seems to be working okay for the ubuntu iso.

**Comment by cawilliamson** [comment]
I was fiddling around - could have been a bug I fixed earlier.

Ok - so what's the current problems you've got with this? I'm kinda confused where we are at this point.

**Comment by snazzybunny** [comment]
For some reason, I'm missing update-initramfs on a fresh install, which is weird. That's why there's no initrd.

**Comment by snazzybunny** [comment]
That worked! Thanks for the help.

**Comment by cawilliamson** [comment]
Ahhhh - I think I know why this is.

I think the liveboot support packages overwrite update-initramfs with their own cooky version.

I have now added a fix for this which should prevent this odd behaviour.

**Comment by snazzybunny** [comment]
Yea exactly.

**Comment by cawilliamson** [comment]
I hate to ask... but... could you try again too? :)

The first fix I added was a bit hashy - this one should be better.

**Comment by snazzybunny** [comment]
It works now. Do you want me to remove the initrd and the symlink?

**Comment by cawilliamson** [comment]
Nah, just run gpd-update and make sure it doesn't do anything daft is all I need.

No need to delete anything.

**Comment by snazzybunny** [comment]
No errors:

TASK [xorg : copy gpd-rotate files] *************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item={u'dest': u'/etc/X11/Xsession.d/01gpd-rotate', u'src': u'files/rotate/01gpd-rotate', u'mode': u'0644'})
ok: [localhost] => (item={u'dest': u'/etc/X11/xinit/xinitrc.d/01gpd-rotate', u'src': u'files/rotate/01gpd-rotate', u'mode': u'0777'})
ok: [localhost] => (item={u'dest': u'/etc/gpd/rotate.conf', u'src': u'files/rotate/gpd-rotate.conf', u'mode': u'0644'})
changed: [localhost] => (item={u'dest': u'/usr/local/sbin/gpd-rotate', u'src': u'files/rotate/gpd-rotate.py', u'mode': u'0777'})
ok: [localhost] => (item={u'dest': u'/etc/systemd/system/gpd-rotate.service', u'src': u'files/rotate/gpd-rotate.service', u'mode': u'0644'})

msg: All items completed

RUNNING HANDLER [xorg : enable gpd-rotate] ******************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=45   changed=3    unreachable=0    failed=0

**Comment by snazzybunny** [comment]
Thanks dood.

**Comment by cawilliamson** [comment]
Glad to help - now I can finally close this one off! :D
