### ISSUE TITLE
ISO won't boot

### ISSUE THREAD

**Issue by RevoltsRevolution** [cawilliamson/ansible-gpdpocket#63]
After succesfully getting the bootstra.iso and looking it up under root (at least in my case) and performing the dd command, the fresh usb stick won't boot. I tried to set it right in the bios but even then (and after disabling all the other boot options) I still am not able to boot into the kali iso I did with the script. Everything inside the terminal looks fine - zero errors. However I was a bit curious about the size - the kali live iso is around 2gb big, the bootstrap iso is almost 12 - is that intended? 

Before you ask - yes, the stick works and I used it countless times for booting up other isos, including kali. ;) 

It's a Sandisk Ultra Fit 32GB stick, if that helps in any way. I also used Etcher after no success in the dd commands, but same output. It shows up as UEFI partition in the bios, but nothing to boot into  

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Herst** [comment]
You could try – but this is take some effort – to try to boot it from the UEFI shell. You can enter the UEFI shell, e.g. by pressing F8 when the device comes up and choosing "UEFI shell" (or similar) there and then pressing Esc to prevent starting `startup.nsh`; but I have no idea what to do next, whenever I used the UEFI shell I had to look-up everything anew.

And of course this only works if the device is really correctly detected by the BIOS.

**Comment by RevoltsRevolution** [comment]
But shouldn't it boot up from the beginning? Or is everyone doing those shell steps? :/

**Comment by cawilliamson** [comment]
@RevoltsRevolution 

Can you point me to the ISO you're using so I can try this?

As for the 2->12GB stuff - that doesn't sound right. I'll look in to that.

**Comment by RevoltsRevolution** [comment]
That's the iso I'm using: 

http://cdimage.kali.org/kali-2017.1/kali-linux-2017.1-amd64.iso

**Comment by cawilliamson** [comment]
@RevoltsRevolution - I'm just building a Kali image now and will check back in shortly.

I did want to ask though - did you try booting by hitting ESC to enter BIOS, then going to the last tab (in any BIOS version) and selecting your Sandisk Ultra Fit? It should work with that device - I have the 128GB version of the same thing and have had no problems (and I've had to boot a LOT of distros and builds as you can imagine! :))

**Comment by RevoltsRevolution** [comment]
Not esc but del to enter bios - yeah the stick is awesome. It always worked like a charm, just not here - it's like a force not wanting me to get the gpd working... lol 

Tried it with the latest release, now the iso is around 3 gb big instead of 12, but still not booting :/

**Comment by cawilliamson** [comment]
It's always been escape for me.

Does it show up in the boot list within BIOS though?

**Comment by RevoltsRevolution** [comment]
The sandisk partition, yeah. It's a UEFI partition but is ignored once I save and restart - it boots either in windows or ubuntu, but not from the stick

**Comment by cawilliamson** [comment]
I have just added various fixes for ISO creation and I believe this should now be resolved.

Could you create a new image, dd it to a USB drive and then test again? :)

As for this "booting from USB drive" stuff - that's not how people are doing this. What you do is go to the last tab in BIOS (Well, EFI), navigate to the drive you want to boot from and literally hit the return key. I haven't changed the boot order on my GPD Pocket - I simply enter BIOS, select the drive and hit enter to boot from it.

**Comment by RevoltsRevolution** [comment]
Just tried it. After what you said I used the esc button and also went to the last tab in the bios - I give you a list of what I see now. 

Boot override: 
UEFI: Built-in EFI shell 
Windows Boot Manager 
ubuntu 
UEFI: CD/DVD Drive* 
UEFI: :SanDisk, Partition 1* 

Both the points marked by me with * are only visible when I use the usb stick. If I hit enter on the Drive, I boot just into my regular ubuntu partition. If I hit enter on the Partition 1 thingy, the bios just flashes for half a second but nothing happens at all... :/ 

Tell me, if it works on your gpd - what is the _exact_ thing you do with the dd command? 

Mine is: 

sudo fdisk -l /dev/sd* 

then: 

sudo dd bs=1M if=~bootstrap.iso of=/dev/sdc 

I had to use a big M because otherwise it gives out an error. And sudo too because otherwise the permissikns are denied. I cut and pasted the bootstra.iso from root to the home folder. In the fdisk command (which needs sudo aswell) I used the disk which has 28.7GB (in my case the 32gb drive) - is there something I'm doing wrong? Does it has to be sdc2 or something?

**Comment by cawilliamson** [comment]
`~bootstrap.iso`?

You should probably be using `/root/bootstrap.iso`

The dd command I use is on mac so the only difference that I use `bs=1m` instead of `bs=1M` and different disk paths.

`/dev/sdc` sounds right (as long as `/dev/sdc` is your USB drive of course)

**Comment by RevoltsRevolution** [comment]
Well I cut and pasted the iso to the home folder... ;)

Is there even a difference between the dd command and the program etcher? And it boots on your device?

**Comment by cawilliamson** [comment]
Ok so three things I've just noticed from booting the 17.04 ISO (yes, on the GPD Pocket!)

1.) It DOES boot the latest kernel and initrd

2.) It *DOES* boot.

3.) Annoyingly their splash screen breaks rotation so I'll have to disable that but it's purely cosmetic.

Wait - you're not trying to boot using the USB-C port are you? Or via a hub of some sort? USB drive -> USB-A port = successful boot for me. Changing the initramfs image wont change that issue you're having (though

**Comment by RevoltsRevolution** [comment]
Nope, directly into the usb port. No hub no usb c - guess your post got cut? 

Question regarding the bs=1m/M thingy... What is that? If I use a lowercase m, it says "invalid number" - do I use google I only find it with an uppercase. Is this maybe the problem? From what I read it's to fasten the writing...?

**Comment by cawilliamson** [comment]
bs = block size - in short, yes faster writing.

That's not the issue though - in short: Linux = lower case, macOS = upper case. I'm using mac to dd the image, you're using Linux. That's all - red herring I'm afraid.

Tell you what - have you tried writing the *unchanged* Ubuntu image to it using `dd`? Does that boot?

**Comment by RevoltsRevolution** [comment]
Ubuntu or kali? 

Ubuntu worked using Etcher. Haven't tried it with dd but can look into it 

Kali booted when I used etcher (before your github post I wasn't aware of the dd command at all)

And by the way... Why is there a setup.exe in the root of the stick after it got written? I thought linux is unable to understand exe files, like osx. I can also try osx... As I said my ubuntu version is on a macbook. :)

**Comment by cawilliamson** [comment]
1.) Ubuntu

2.) Never used etcher - no idea what it does to be honest.

3.) ^ See point 2

4.) The setup.exe is so that you can start the installation from Windows - it's nothing to do with my script though - it's a Ubuntu thing.

**Comment by RevoltsRevolution** [comment]
So I tested it now. 

I used dd on OSX and the bootstrap iso didn't work. However the untouched ubuntu iso did work using the dd command... 

So now what? :/ 

Tried the bootstrap command on osx too but it gave an error pretty quick

**Comment by cawilliamson** [comment]
Could you try bootstrapping the ISO again?

There were problems with the wrong shell being used when building on certain distros - Ubuntu being one of them.

**Comment by cawilliamson** [comment]
I'm closing this one since I believe the Ubuntu problem is now with bug #82 

If you have additional problems booting your Ubuntu ISO please update in ticket #82.

Thanks!
