### ISSUE TITLE
Large images

### ISSUE THREAD

**Issue by cawilliamson** [cawilliamson/ansible-gpdpocket#64]
There seems to be an issue where the bootstrapped ISO is much larger than it should be.

I'm not currently sure why this is so will investigate and hopefully get this fixed.

**Comment by msaong** [comment]
I test with fedora iso(1.5G ISO), and get a 10G ISO in the last....

i check the file system, i notice these is new directory named squashfs ,it take 7GB space

`root@morlen-virtual-machine:/var/tmp/bootstrap-iso/squashfs/LiveOS# ls -l
total 6605356
-rw-rw-r--. 1 root root 6981419008 8月  17 09:23 rootfs.img
`

**Comment by msaong** [comment]
![20170817103814](https://user-images.githubusercontent.com/25732857/29393763-5ff13d04-8338-11e7-8f67-d0f166a530cb.png)

**Comment by cawilliamson** [comment]
This is now resolved.
