### ISSUE TITLE
Fedora installer fails to boot

### ISSUE THREAD

**Issue by msaong** [cawilliamson/ansible-gpdpocket#66]
Hi,

I fork the copy and mod the shell, now i can generate the ISO, the size of the orginal is 1.5G, and the new ISO take me 10GB.
It's nothing. But after i try to boot via the new ISO, it show me the issue below, can you please advice what happened?

![20170817103146](https://user-images.githubusercontent.com/25732857/29393618-6430200c-8337-11e7-92bd-6053c8a04b82.jpg)

**Comment by cawilliamson** [comment]
This is a known issue but I had failed to add this to the known issues list in the README - sorry about that.

I will investigate this as time permits and hope to have a resolution within the next few days - work has been hectic at the minute.

**Comment by cawilliamson** [comment]
@msaong Could you try this again and let me know if the issue still persists?

**Comment by Sonique** [comment]
Have the same issue. 
In emergency console executed:

    # cd /etc/systemd/system/
    # cp /usr/lib/systemd/system/iscsi.service 
    # systemctl disable iscsi.service
    # systemctl enable iscsi.service

But after that stop at `A start job is running for dev-mappe...r`

**Comment by msaong** [comment]
@cawilliamson i check the file between the orginal ISO and the new respin one, i notice a big different:

We can find there is a file name as squashfs.img in the LivsOS dir.
We can open the squashfs.img via 7-zip, and find there is a rootfs.img the the LivsOS dir.

Ok, the different is about this file:
I can open the rootfs.img of orginal ISO vai 7-zip.
But i can't open the rootfs.img of new respin ISO via 7-zip.

I think we can slove this the issue can fix.
