### ISSUE TITLE
TASK [iso : extract squashfs image] step fails with antergos

### ISSUE THREAD

**Issue by snazzybunny** [cawilliamson/ansible-gpdpocket#67]
Cloned repository and tried to make ISOs for ubuntu and antergos. Ubuntu worked fine but the script is showing this error with Antergos:

```
TASK [iso : extract squashfs image] *************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: list object has no element 0\n\nThe error appears to have been in '/home/ole/ansible-gpdpocket2/roles/iso/tasks/main.yml': line 113, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: extract squashfs image\n  ^ here\n"}
	to retry, use: --limit @/home/ole/ansible-gpdpocket2/iso.retry

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=12   changed=4    unreachable=0    failed=1
```

**Comment by glambx** [comment]
Same here, on Debian stable and unstable hosts, building the Debian 9 ISO.

**Comment by snazzybunny** [comment]
Just realized my ubuntu iso is 6.5 gb :o.

**Comment by cawilliamson** [comment]
I'm looking in to the large iso issue elsewhere but this ticket appears to be about the squashfs image not being detected properly for Antergos & Debian so I'll look in to that here and report back.

**Comment by cawilliamson** [comment]
Ok two answers here:

@snazzybunny Antergos is now fixed - that was due to the squashfs image not being found (bad search string on my part - oops!)

@glambx - I am having no problems at all building a debian image - you're not trying to use an "installcd" are you? Those wont work since there is no content in them - it's all pulled down from the web as they're installed - not going to work. You need the "live cd" version of debian.

**Comment by glambx** [comment]
Yep, that was it.  The live CD worked perfectly and my gpdpocket is up and running.  Thanks so much!

**Comment by cawilliamson** [comment]
Awesome - great news @glambx  👍
