### ISSUE TITLE
GRUB entries not updated

### ISSUE THREAD

**Issue by Herst** [cawilliamson/ansible-gpdpocket#83]
Just like the person in #73 I ended up with an old kernel which wouldn't update when just doing `gpd-update`, so I did the fix with doing `rm -rf /usr/src/linux-jwrdegoede` before and then it wouldn't automatically boot after a reboot because it tried to boot the old kernel. Doing `sudo grub-update` fixed it.

**Comment by icebal** [comment]
person from #73 here. the ansible script ran grub-mkconfig for me at the end. what distro are you running and do you have grub-makeconfig or do you just havegrub-update?

**Comment by Herst** [comment]
Oops, should have mentioned that my distro is Ubuntu 17.04.

**Comment by icebal** [comment]
can you check to make sure you have the grub-mkconfig command, and not the ubuntu renamed grub-update one?

**Comment by snazzybunny** [comment]
16.04 vanilla - installed ansible-gpdpocket and ran system script. Grub entries did not update.

**Comment by icebal** [comment]
can you guys throw the script output onto pastebin or hastebin? i can take a look until @cawilliamson gets rested up from working on this all weekend

**Comment by cawilliamson** [comment]
I've added a change I will should fix this (or at the very least - error out and let you know it couldn't update boot records.)

If someone could remove `/usr/src/linux-*` and then try again and let me know if this works?

Thanks!

**Comment by cawilliamson** [comment]
I'm closing this one for now (you can re-open if needed @Herst) since I'm comfortable this is now resolved.

The Ubuntu specific problems can be added to #82 since I believe that's where the remaining problem is.

**Comment by cawilliamson** [comment]
@icebal As a side note - I'm almost certain Ubuntu contains both `grub-update` and the grub package default grub-mkconfig (though it may be renamed grub2-mkconfig - fix added by you there. :))
