### ISSUE TITLE
Build for ubuntu systems broken: check for grub-mkconfig uses wrong path.

### ISSUE THREAD

**Issue by nexus511** [cawilliamson/ansible-gpdpocket#85]
Commit 554c592 breaks build on ubuntu (maybe debian) based images. Reason is that grub-mkconfig is located in /usr/sbin rather than /usr/bin.

**Comment by cawilliamson** [comment]
This is now resolved (based on your work, thanks!) in the latest commit.

I merged your changes in with a change I was doing (which sadly would clash - split up initrd and grub steps.)
