### ISSUE TITLE
Review of recent PR: "Remove explicit cloning from external repository when we can avoid that."

### ISSUE THREAD

**Issue by Herst** [cawilliamson/ansible-gpdpocket#87]
Tried the review interface, please see https://github.com/cawilliamson/ansible-gpdpocket/pull/84/files/8b5c80926c67f3af3a8e8f6578ed98d66c4b2935

Since the PR is closed it can't be reopened even if the github interface implies that it can be.

If you are OK with it I will create a pull request.

**Comment by cawilliamson** [comment]
Is this about the `--git` change?

If so - I've already added it and credited you in the commit. :)

**Comment by Herst** [comment]
I'm too slow. :)
