### ISSUE TITLE
old gpd pocket ubuntu 17.04 run system.sh  for a long time

### ISSUE THREAD

**Issue by Xianbei233** [cawilliamson/ansible-gpdpocket#89]
i use the ubuntu 17.04 which was supported in reddit  2 months ago and used the old ansible script. And now i want to update the system script and use the new ansible. but now i have been running bootstrap-system.sh for 4 hours. Is there any problem?
![image](https://user-images.githubusercontent.com/16370242/29496365-9d6f6b6a-8603-11e7-8fd8-4525322f8401.png)

**Comment by cawilliamson** [comment]
You need to run `bash bootstrap-system.sh` not `sh bootstrap-system.sh` :)
