### ISSUE TITLE
touchegg included for multitouch gestures

### ISSUE THREAD

**Issue by icebal** [cawilliamson/ansible-gpdpocket#92]
this can be either included for awesome sauce-ness, or closed as WONTFIX so people know about it. touchegg is an app that allows multi-input gestures like 2 finger scrolling, tap and hold for right click, 3 finger dragging to change workspaces, and so on. this allows the Pocket's touchscreen to act more like a regular laptop or tablet touchscreen. it is packaged in all the major distros.

**Comment by Herst** [comment]
Thinking out loud: Maybe info like this is better something for the Linux@GPD-Pocket thread on Reddit? Maybe a list could be created with neat tools/settings-not-changed-by-the-playbooks/tips-and-tricks for Linux on the device where things like this could be collected, what do you think Reddit mod. @cawilliamson?

**Comment by icebal** [comment]
was thinking that or just a simple wiki page on here.

**Comment by cawilliamson** [comment]
@icebal Tell you what - if you do one of the following I'll include it:

1.) Provide a pull request including it.
Or 2.) Provide the config files to get it setup and working properly (non-distro specific.)

Happy either way - it does sound very cool but I don't want to spend a whole lot of time on it when things like the Fedora installer are so quirky on GPD Pocket yet.

**Comment by Herst** [comment]
@cawilliamson Sorry for hijacking this thread, but the link in your Reddit post is broken.

(Feel free to delete this message.)

**Comment by icebal** [comment]
totally fine with that :) i understand you have more important things to look into. i'll start getting the request ready and a sane default config.

**Comment by DavidCWGA** [comment]
I wouldn't like this to change the default behavior of the touchscreen, though.

**Comment by icebal** [comment]
the default behavior of the touchscreen is 1 input only left click. touchegg sane defaults is the same for 1 tap, but allows you to have tap-and-hold, 2 finger gestures, and 3 finger gestures. what i have found out though, is touchegg is the way to get multiple finger gestures. libinput doesn't recognize the driver as multi-touch capable. the whole reason for touchegg to even be an option is to have the same capabilities as the windows version, as well as what you have for phones, tablets, other touchscreen laptops, etc.

hope this explains things well enough :)

**Comment by nexus511** [comment]
Just tested touchegg on my system. That looks pretty much like something you totally want to have in there.

I will try to merge this into my Ubuntu package stuff including some sane default configuration. As soon as this works properly I can create a PR and @cawilliamson can decide, if it is worth to merge it.

I can will test this for ubuntu/xubuntu/mint for now. So I would create a PR based on those systems. If anyone of you guys would be able to extend that for other distributions, that would be very welcome.

**Comment by icebal** [comment]
i have been doing it with arch and xfce, and thedefault config is sane. the only thing that would have to be done is push the systemd service and enable/start it (doesnt include one by default)

**Comment by nexus511** [comment]
Are you sure that systemd is the place to start it? I would have done that using an x11-init script.

**Comment by nexus511** [comment]
@icebal 

I would basically suggest something like this to be placed into the xorg startup directories:

https://github.com/nexus511/gpd-ubuntu-packages/blob/development/Charlie/packages/gpdpocket-touchegg-config/files/01_touchegg

And alongside placing this configuration file to the default configuration directory:

https://github.com/nexus511/gpd-ubuntu-packages/blob/development/Charlie/packages/gpdpocket-touchegg-config/files/touchegg.conf

That should basically ensure that touchegg is started on X11 startup in the right X session for each user.

**Comment by icebal** [comment]
That looks perfect :)

**Comment by nexus511** [comment]
Okay. I try to get it merged into the ansible stuff later.

**Comment by nexus511** [comment]
I have merged the changes into my forked repository. It would be great, if anyone could basically test it.

You can just checkout my branch to the same directory you already cloned this project to by calling

```
git remote add nexus511 https://github.com/nexus511/ansible-gpdpocket.git
git fetch nexus511
git checkout feature/merge_multitouch
```

Afterward you can just build the current version using

```
bash bootstrap-iso.sh <imagefile>
```

If everything works, you can switch back to the original master using

```
git checkout master
git remote remove nexus511
```

If anyone can inform me (maybe @icebal) if it works it would be great. I would then create a pull request based on the changes.
