### ISSUE TITLE
double free in appstreamcli

### ISSUE THREAD

**Issue by schwindp** [cawilliamson/ansible-gpdpocket#94]
Using an uptodate clone of this repo and xubuntu-16.04-desktop-amd64.iso, bootstrapping fails in 
TASK [iso : bootstrap guest (this may take a while)] 

```
*** Error in `appstreamcli': double free or corruption (fasttop): 0x0000000002fe7d30 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7f4fa570a725]
/lib/x86_64-linux-gnu/libc.so.6(+0x7ff4a)[0x7f4fa5712f4a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f4fa5716abc]
/usr/lib/x86_64-linux-gnu/libappstream.so.3(as_component_complete+0x439)[0x7f4fa5a8ed19]
/usr/lib/x86_64-linux-gnu/libappstream.so.3(as_data_pool_update+0x44a)[0x7f4fa5a8ff0a]
/usr/lib/x86_64-linux-gnu/libappstream.so.3(as_cache_builder_refresh+0x1c2)[0x7f4fa5a85272]
appstreamcli(ascli_refresh_cache+0x12e)[0x4049de]
appstreamcli(as_client_run+0x6fb)[0x403ceb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f4fa56b3830]
appstreamcli(_start+0x29)[0x403519]
```

According to https://askubuntu.com/questions/943832/after-automatic-upgrade-apt-get-update-cause-error-in-appstreamcli-double-f this seems to be a current bug in Xubunt 16.03, which seems to be resolvable removing appstream (if not needed here).

(Building on an Ubuntu 16.04 Server)

**Comment by nexus511** [comment]
Ah. Took me a while to get this: You are using xubuntu-16.04 and not xubuntu-16.04.3, aren't you?

This version has a flaw in the updater so it will fail even if you try update an installed system.

**Comment by schwindp** [comment]
Uhm. Looks I was out of caffeine. Thanks anyway.
