### ISSUE TITLE
Dangerous file permissions on several files

### ISSUE THREAD

**Issue by nexus511** [cawilliamson/ansible-gpdpocket#97]
I have created two pull requests as there are currently scripts that are executed with root permissions and are world writable created on the destination images.

Any running process on the system can basically write to those files and gain root permissions on the next start of those processes.

Those files are automatically spawned as services during boot:

- /etc/X11/xinit/xinitrc.d/01gpd-rotate
- /usr/local/sbin/gpd-rotate
- /usr/local/sbin/gpd-fan
- /lib/systemd/system-sleep/gpd-fan

Additionally this script has to be called as root to work properly:

- /usr/local/bin/gpd-update

All those files should never be writable by group or others. Users should update the permissions on their devices as updates will not come via package management for those.

**Comment by cawilliamson** [comment]
Cheers! Merged your PRs.

**Comment by enthusi** [comment]
Thanks to both of you for working so hard on this - we all benefit massively :)
